Lidarr/Lidarr

src/UI/Artist/Details/AlbumLayout.js
src/UI/Cells/ArtistMonitoredCell.js

Fix Double Quote and AlbumID variable for Search
NO
Fixes a JS double quote codacy issue and passes correct albumId variable on search call.

Fix Double Quote and AlbumId variable for Search

---

src/NzbDrone.Core/Configuration/ConfigFileProvider.cs

Fixed: Ensure an API Key is set when starting Lidarr
NO
Reference Sonarr/Sonarr@6bbe4ce
Reference Radarr/Radarr@7af8803

Fixed: Ensure an API Key is set when starting Lidarr

---

src/UI/index.html
src/UI/login.html

Remove redundant IE meta tag as we use http header instead
NO
Radarr/Radarr@b1c5dd8
Sonarr/Sonarr@2ae41a3

Fixed: Remove redundant IE meta tag as we use http header instead

---

src/UI/Artist/Edit/EditArtistViewTemplate.hbs

Fixed: Album Folder Toggle/Artist Name in Edit Artist Popup
NO
Fixes the AlbumFolder toggle switch and the Artist Name not showing in the Artist Edit Popup Window

Fixed: Album Folder Toggle/Artist Name in Edit Artist Popup

---

src/NzbDrone.Core/Music/TrackRepository.cs
src/UI/Artist/Delete/DeleteArtistTemplate.hbs
src/UI/Artist/Delete/DeleteArtistView.js

Fixed: Artist Delete, Track Delete when Artist Delete
NO
- Fixes Artist Delete template now shows correct template.
- Tracks are now deleted from DB during artist delete. (When using the join query, we can never find artist during a delete as its deleted first. Thus no tracks were returned in query. Changing this to left join will also work if we absolutely need Artist returned with results.)

Fixed: Artist Delete, Track Delete when Artist Delete

---

src/NzbDrone.Core/Indexers/Waffles/WafflesRequestGenerator.cs

Add Paging to Waffles Requests
NO
Adds paging to waffles requests. Returns 75 results now instead of 15.

Add Paging to Waffles Requests

---

src/NzbDrone.Core/IndexerSearch/AlbumSearchCommand.cs

NO
Change `AlbumSearchCommand` to public visibility. This was missed before and caused an issue with searching for albums.
* Unreported: Error when searching for album.

Fixed: Change AlbumSearchCommand to public to resolve error when searching

---

src/NzbDrone.Core.Test/Housekeeping/Housekeepers/CleanupOrphanedAlbumsFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedAlbums.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

NO
Create a housekeeper for albums leftover in DB that have no valid artist association. 
#64 
*

Create Orphaned Albums Housekeeper

---

src/NzbDrone.Core/MetadataSource/SkyHook/Resource/AlbumResource.cs
src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs

NO
Change `AlbumResource.Label` to `AlbumResource.Labels` due to the change in lidarr/lidarrapi.metadata#13.
None

Change AlbumResource label to labels due to the change metadata

---

src/NzbDrone.Core.Test/IndexerTests/HeadphonesTests/HeadphonesFixture.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs
src/NzbDrone.Core/Download/UsenetClientBase.cs
src/NzbDrone.Core/History/HistoryRepository.cs
src/NzbDrone.Core/Indexers/Headphones/Headphones.cs
src/NzbDrone.Core/Indexers/Headphones/HeadphonesRssParser.cs
src/NzbDrone.Core/Indexers/RssParser.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Parser/Model/ReleaseInfo.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Fix Headphones Download Auth by storing auth string in releaseInfo for use by client base to grab the nzb. 
Adds secondary parsing by comparing search criteria to release title. 
#149 
*

Fix Headphones Download Auth, Add Special Parsing

---

frontend/src/Settings/Profiles/Metadata/EditMetadataProfileModalContent.js
frontend/src/Settings/Profiles/Metadata/EditMetadataProfileModalContentConnector.js
frontend/src/Settings/Profiles/Metadata/ReleaseStatusItem.js
frontend/src/Settings/Profiles/Metadata/ReleaseStatusItems.js
src/Lidarr.Api.V1/Profiles/Metadata/MetadataProfileModule.cs
src/Lidarr.Api.V1/Profiles/Metadata/MetadataProfileResource.cs
src/Lidarr.Api.V1/Profiles/Metadata/MetadataValidator.cs
src/NzbDrone.Core.Test/Profiles/Metadata/MetadataProfileRepositoryFixture.cs
src/NzbDrone.Core/Datastore/Converters/ReleaseStatusIntConverter.cs
src/NzbDrone.Core/Datastore/Migration/012_add_release_status.cs
src/NzbDrone.Core/Datastore/TableMapping.cs
src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
src/NzbDrone.Core/Music/ReleaseStatus.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Profiles/Metadata/MetadataProfile.cs
src/NzbDrone.Core/Profiles/Metadata/MetadataProfileService.cs
src/NzbDrone.Core/Profiles/Metadata/ProfileReleaseStatusTypeItem.cs

YES
Adds ability to filter library by Release Status using metadata profiles
Default is to official only
#202

Added: Add Release Status to Metadata Profile, Default to Official Only

---

appveyor-package.sh

NO
Fix MacOS builds. A bit hacky but it seems to work to get around windows build environment thinking Lidarr is same as Lidarr.exe
#209 
*

Fixed: MacOS Appveyor builds don't inlcude startup script

---

src/NzbDrone.Core.Test/MusicTests/AlbumRepositoryTests/AlbumRepositoryFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/GetLocalTrackFixture.cs
src/NzbDrone.Core/Music/AlbumRepository.cs
src/NzbDrone.Core/Music/AlbumService.cs
src/NzbDrone.Core/Parser/Parser.cs
src/NzbDrone.Core/Parser/ParsingService.cs

NO
Check if an album has a MusicBrainz Release Id during Import/Scan and check if a match in DB. If so, bypass metadata lookup against LidarrAPI.
Feature #227

Check for MusicBrainz Release Id during Scan (#227)

---

src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Enhances our cleaning code to ensure feat. ARTIST, ft. ARTIST, or featuring ARTIST is stripped before matching. 
* #283

Added cases to strip feat. from track titles.

---

src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/GetLocalTrackFixture.cs
src/NzbDrone.Core/Music/TrackService.cs
src/NzbDrone.Core/Parser/ParsingService.cs

NO
* Fallback to non-cleaned track titles when a cleaned track is not matched in the database.
* When matching tracks on an album, include the track number as some albums have tracks with same name. Fixes #287 
Fixes #287

Parser Enhancements

---

src/NzbDrone.Core/Jobs/TaskManager.cs
src/NzbDrone.Core/Music/ShouldRefreshAlbum.cs
src/NzbDrone.Core/Music/ShouldRefreshArtist.cs

NO
Sets Artist Refresh Scan to 24 hours instead of 12
Sets old album refresh interval to 60 days instead of 30
Sets continuing artist refresh interval to 2 days instead of 12 hours.

Changed: Modify Artist Update Intervals

---

src/NzbDrone.Common/Http/HttpHeader.cs
src/NzbDrone.Core.Test/MediaCoverTests/CoverExistsSpecificationFixture.cs
src/NzbDrone.Core.Test/MediaCoverTests/MediaCoverServiceFixture.cs
src/NzbDrone.Core/MediaCover/CoverAlreadyExistsSpecification.cs
src/NzbDrone.Core/MediaCover/MediaCoverService.cs

NO
Fanart.tv does not return Content-Length for HEAD requests, thus we need to use something else to compare local image to server image. This change uses file modified date to check for same image.

Fixed: Don't download artist images if match existing

---

src/NzbDrone.Core.Test/NotificationTests/SynologyIndexerFixture.cs
src/NzbDrone.Core/MediaFiles/Events/AlbumImportedEvent.cs
src/NzbDrone.Core/MediaFiles/TrackImport/ImportApprovedTracks.cs
src/NzbDrone.Core/Notifications/AlbumDownloadMessage.cs
src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/NotificationService.cs
src/NzbDrone.Core/Notifications/Synology/SynologyIndexer.cs

NO
Send OldFiles and NewFiles with OnAlbumDownloaded Event.
Handle Synology add and delete with a OnAlbumDownloaded Event.
Add OldFiles and AddedFiles to Custom Script variables for OnAlbumDownloaded Event.
Fixes #324

New: Expand OnAlbumDownload, Add Synology handling

---

src/NzbDrone.Core.Test/MusicTests/RefreshAlbumServiceFixture.cs
src/NzbDrone.Core/Music/RefreshAlbumService.cs
src/NzbDrone.Core/Music/RefreshArtistService.cs

NO
Override album refresh logic when triggered by a manual artist refresh.

Changed: Force album refresh when artist refresh manually triggered

---

frontend/src/Activity/History/HistoryRow.js
frontend/src/Activity/Queue/QueueRow.js
frontend/src/Album/AlbumTitleLink.js
frontend/src/Album/Details/AlbumDetails.js
frontend/src/Artist/Details/AlbumRow.js
frontend/src/Artist/Index/Table/ArtistIndexRow.js
frontend/src/Settings/MediaManagement/Naming/NamingModal.js
frontend/src/Wanted/CutoffUnmet/CutoffUnmetRow.js
frontend/src/Wanted/Missing/MissingRow.js
src/Lidarr.Api.V1/Albums/AlbumResource.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
src/NzbDrone.Core/Datastore/Migration/018_album_disambiguation.cs
src/NzbDrone.Core/MetadataSource/SkyHook/Resource/AlbumResource.cs
src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
src/NzbDrone.Core/Music/Album.cs
src/NzbDrone.Core/Music/RefreshAlbumService.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Organizer/FileNameBuilder.cs
src/NzbDrone.Core/Organizer/FileNameSampleService.cs

YES
This adds ability for Lidarr to store and use album disambiguation from Musicbrainz. Adds disambiguation to certain places in UI (Artist Album List, History, Queue, Wanted) and allows user to use the disambiguation in album folder and track naming models.
#430 
*

New: Added album disambiguation to UI [ex. Weezer (Blue Album)]

---

src/NzbDrone.Core.Test/IndexerSearchTests/SearchDefinitionFixture.cs
src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
src/NzbDrone.Core/IndexerSearch/Definitions/AlbumSearchCriteria.cs
src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs
src/NzbDrone.Core/Indexers/Gazelle/GazelleRequestGenerator.cs
src/NzbDrone.Core/Indexers/Headphones/HeadphonesRequestGenerator.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
src/NzbDrone.Core/Indexers/Omgwtfnzbs/OmgwtfnzbsRequestGenerator.cs
src/NzbDrone.Core/Indexers/Rarbg/RarbgRequestGenerator.cs
src/NzbDrone.Core/Indexers/Waffles/WafflesRequestGenerator.cs

NO
Searches fail on Newznab (and maybe some torrent indexers) when artists or albums have special characters. This builds a clean query to use for searching.
Fixes:
Mötley Crüe
AC/DC
Titles with ellipsis (ex. …and Justice for All)
Titles with colons (ex. American III: Solitary Man)
#410 - not fixed but improved 
*

Fixed: Search fails for many artist and albums with specials

---

src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
This adjusts the regex to allow text in front and back and only clean what is in parenthesis in case of back to back info.
Cases:
Meteora (iTunes Deluxe Edition)

Fixed: Allow text in front of cleaned Album/Track tag

---

README.md

NO
Add a one-click shortcut to the Wiki page explaining how to get Lidarr with Docker.

Make the docker badge link to the Docker wiki page

---

src/NzbDrone.Common/Extensions/StringExtensions.cs
src/NzbDrone.Core.Test/MusicTests/AlbumRepositoryTests/AlbumRepositoryFixture.cs
src/NzbDrone.Core.Test/MusicTests/TitleMatchingTests/TitleMatchingFixture.cs
src/NzbDrone.Core/Music/AlbumRepository.cs
src/NzbDrone.Core/Music/AlbumService.cs
src/NzbDrone.Core/Music/TrackService.cs
src/NzbDrone.Core/Parser/ParsingService.cs

NO
Add fuzzy matching to album and track names on import.
Fix matching albums when name is entirely special characters
This adds fuzz to album and track title matching when importing.  Means that the import is generally more successful.
This also fixes the case where the album name is entirely special characters, which means that `CleanName` is empty.

Fuzzy matching

---

frontend/src/Components/SignalRConnector.js
frontend/src/Utilities/Filter/getFilterValue.js
frontend/src/Utilities/pagePopulator.js
frontend/src/Wanted/CutoffUnmet/CutoffUnmet.js
frontend/src/Wanted/CutoffUnmet/CutoffUnmetConnector.js
frontend/src/Wanted/Missing/Missing.js
frontend/src/Wanted/Missing/MissingConnector.js

on the wanted page .. the monitor/unmonitor selected button was not changing corresponding to the filter selected....
nor was it properly carrying out its function.
It should now work.
NO
The Unmonitor/Monitor Selected button was not changing with the currently selected filter, nor was it actually carrying out its function. it should now work properly.
Note: The changes do make the button work as expected. I checked to make sure these changes wont break anything else - and i dont think so - but i am not sure. I really dont know the lidarr code much at all so please verify that I didnt break anythnig substantial.

Wanted Monitor/Unmonitor Selected button fixed

---

src/NzbDrone.Core/Indexers/Gazelle/Gazelle.cs

NO
After Apollo.Rip went down a few months ago, Orpheus has come up with the same DB as Apollo except under a different URL. It uses the Gazelle API, which means the same configuration will work with Apollo.

Update Apollo with Orpheus

---

src/NzbDrone.Core/MediaFiles/DiskScanService.cs

NO
The extra file importer will try to import in-transit audio files which can mean they never get properly renamed. This makes everything ignore the partial files.

Fixed: Ignore .partial~ files

---

frontend/src/Activity/Queue/QueueRow.css
frontend/src/Activity/Queue/QueueRow.js
frontend/src/Activity/Queue/RemoveQueueItemModal.js
frontend/src/InteractiveSearch/InteractiveSearchRow.js
src/Lidarr.Api.V1/Indexers/ReleaseModule.cs
src/Lidarr.Api.V1/Queue/QueueResource.cs
src/NzbDrone.Core.Test/DecisionEngineTests/PrioritizeDownloadDecisionFixture.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionPriorizationService.cs
src/NzbDrone.Core/History/HistoryService.cs
src/NzbDrone.Core/Queue/Queue.cs
src/NzbDrone.Core/Queue/QueueService.cs

NO
Allows you to download any search result in the interactive search dialog, even if the album or artist couldn't be parsed. Ones that couldn't be parsed get a red icon. 
* #441

Fixed: Allow downloading any search result

---

src/NzbDrone.Common.Test/ExtensionTests/FuzzyContainsFixture.cs
src/NzbDrone.Common.Test/LevenshteinDistanceFixture.cs
src/NzbDrone.Common.Test/NzbDrone.Common.Test.csproj
src/NzbDrone.Common/Extensions/FuzzyContains.cs
src/NzbDrone.Common/Extensions/StringExtensions.cs
src/NzbDrone.Common/NzbDrone.Common.csproj
src/NzbDrone.Core.Test/MusicTests/AlbumRepositoryTests/AlbumRepositoryFixture.cs
src/NzbDrone.Core.Test/MusicTests/AlbumServiceFixture.cs
src/NzbDrone.Core.Test/MusicTests/ArtistRepositoryTests/ArtistRepositoryFixture.cs
src/NzbDrone.Core.Test/MusicTests/ArtistServiceTests/FindByNameInexactFixture.cs
src/NzbDrone.Core.Test/MusicTests/TitleMatchingTests/TitleMatchingFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Music/AlbumRepository.cs
src/NzbDrone.Core/Music/AlbumService.cs
src/NzbDrone.Core/Music/ArtistService.cs
src/NzbDrone.Core/Music/TrackRepository.cs
src/NzbDrone.Core/Music/TrackService.cs
src/NzbDrone.Core/Parser/Parser.cs
src/NzbDrone.Core/Parser/ParsingService.cs

NO
Further improvements to the fuzzy matching:
- Fix FuzzyMatch so that it's symmetric and tweak thresholds
- Improve FuzzyMatch when the two strings to compare have different numbers of words
- Add FuzzyContains which finds the closest substring to a pattern
- Implement fuzzy matching for artists
- Add various permutations of title cleaning for Albums
- Strip out any brackets and their contents from the release name
- Strip out anything after a `-` or a `:` in the release name
- Allow fuzzy substring based matching (but the match must still be better than that for any other albums)
- Allow fuzzy substring based matching for tracks
- Rework exact track matching (which allows matching on substrings) to require a unique match
- Don't assume disc 1 if disc tag missing for tracks (and don't …

Improve the fuzzy matching

---

src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Re-run the release parsing using the search criteria if the release parsed but we couldn't match it to an album/artist.  This particularly helps when the artist contains a `-` like `American Hi-Fi-The Art Of Losing-2003-NHH INT` where the artist is parsed as `American Hi` and the album as `Fi` the first time.

Fixed: Better release parsing in case incorrect parse

---

frontend/src/Components/SignalRConnector.js
frontend/src/InteractiveImport/Album/SelectAlbumModalContentConnector.js
frontend/src/InteractiveImport/Artist/SelectArtistModalContentConnector.js
frontend/src/InteractiveImport/Interactive/InteractiveImportRow.js
frontend/src/InteractiveImport/Track/SelectTrackModalContent.js
frontend/src/Store/Actions/interactiveImportActions.js
src/Lidarr.Api.V1/Lidarr.Api.V1.csproj
src/Lidarr.Api.V1/ManualImport/ManualImportModule.cs
src/Lidarr.Api.V1/ManualImport/ManualImportModuleWithSignalR.cs
src/Lidarr.Api.V1/ManualImport/ManualImportResource.cs
src/NzbDrone.Core.Test/MediaFiles/TrackImport/ImportDecisionMakerFixture.cs
src/NzbDrone.Core/MediaFiles/TrackImport/ImportDecisionMaker.cs
src/NzbDrone.Core/MediaFiles/TrackImport/Manual/ManualImportItem.cs
src/NzbDrone.Core/MediaFiles/TrackImport/Manual/ManualImportService.cs
src/NzbDrone.Core/Parser/ParsingService.cs

NO
Automatically refreshes import decisions when the artist or album is changed in the manual import modal.
Often it's the album that isn't matched and once Lidarr knows the album it can match the tracks.  This means that you can avoid manually setting each track - you'd hopefully just have to set the album and let it work it out.
I've also added the filename to the track select modal, because at the moment once that's open there's no way to see what you're actually choosing a track for.

New: Manual import refreshes decisions when artist/album updated

---

src/NzbDrone.Core.Test/IndexerSearchTests/SearchDefinitionFixture.cs
src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs

YES | NO
This is the [preferred apostrophe on musicbrainz](https://beta.musicbrainz.org/doc/Style/Miscellaneous).

Remove typographic apostrophe

---

src/NzbDrone.Core.Test/Datastore/Migration/023_add_release_groups_etcFixture.cs
src/NzbDrone.Core.Test/MusicTests/RefreshAlbumServiceFixture.cs
src/NzbDrone.Core.Test/MusicTests/RefreshArtistServiceFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Datastore/Migration/023_add_release_groups_etc.cs
src/NzbDrone.Core/Music/AlbumRepository.cs
src/NzbDrone.Core/Music/AlbumService.cs
src/NzbDrone.Core/Music/RefreshAlbumService.cs
src/NzbDrone.Core/Music/RefreshArtistService.cs
src/NzbDrone.Core/Music/RefreshTrackService.cs
src/NzbDrone.Core/Music/TrackRepository.cs
src/NzbDrone.Core/Music/TrackService.cs

NO
Fixes a couple more issues that have shown up in sentry:
1. where `CurrentRelease` is completely null
1. where we have duplicate `ForeignReleaseId` (the previous fix would trip up when trying to assign `ReleaseId` to each `Track`
In 1., I have put in a dummy release so that the migration succeeds and the first medium's tracks will show up in the UI.  This will get deleted and re-created by the metadata refresh (as will all the associated tracks and mapped trackfiles).  For 2. I have put in a fake `ForeignReleaseId` - we know the `AlbumId` is unique so I've used that.  Again, this means the release and any tracks/trackfiles will be deleted and recreated but I can't think of a way we can avoid that.
The second commit fixes up the metadata refreshes.  It makes sure that we deal with the …

Fix more issues with migration 23

---

src/NzbDrone.Core/Music/ReleaseStatus.cs
src/NzbDrone.Core/Music/SecondaryAlbumType.cs

NO
Fixes `DJ-Mix` to `DJ-mix` Secondary Type
Add `Audiobook` Secondary Type - Not quite convinced this is good idea?? Nope
Add `Demo` Secondary Type
Fixes `Promotional` to `Promotion` Release Status
Didn't do a DB migration, user have to re-create or add a new metadata profile to get the new types. Doesn't seem like a huge deal?
Fixes #589  
#453  - This is about as far as I want to go with supporting Audiobooks. Most musicbrainz entries have hundreds of tracks per book and the DB gets flooded fairly quickly which is why this was left out. Thoughts?
*

Fixed: Missing album types, typos in type/status

---

src/NzbDrone.Common.Test/CacheTests/CachedFixture.cs
src/NzbDrone.Core.Test/Files/Identification/CorruptFile.json
src/NzbDrone.Core.Test/Files/Identification/FilesWithMBIds.json
src/NzbDrone.Core.Test/Files/Identification/FilesWithoutTags.json
src/NzbDrone.Core.Test/Files/Identification/InconsistentTyposInAlbum.json
src/NzbDrone.Core.Test/Files/Identification/PenalizeUnknownMedia.json
src/NzbDrone.Core.Test/Files/Identification/PreferMissingToBadMatch.json
src/NzbDrone.Core.Test/Files/Identification/SucceedWhenManyAlbumsHaveSameTitle.json
src/NzbDrone.Core.Test/MediaFiles/MediaFileRepositoryFixture.cs
src/NzbDrone.Core.Test/MediaFiles/TrackImport/Identification/AlbumDistanceFixture.cs
src/NzbDrone.Core.Test/MediaFiles/TrackImport/Identification/IdentificationServiceFixture.cs
src/NzbDrone.Core.Test/MediaFiles/TrackImport/Identification/TrackGroupingServiceFixture.cs
src/NzbDrone.Core.Test/ParserTests/FingerprintingServiceFixture.cs
src/NzbDrone.Core/MediaFiles/TrackImport/Identification/IdentificationService.cs
src/NzbDrone.Core/MediaFiles/TrackImport/Identification/IdentificationTestCase.cs
src/NzbDrone.Core/MediaFiles/TrackImport/Identification/TrackGroupingService.cs
src/NzbDrone.Core/Parser/FingerprintingService.cs

NO
Fixes the failing tests and issues with new track parsing @gismo2004 discovered:
- Fix when track numbers are null (because taglib parsing failed)
- Fix when release date for a release is null
- Fix when fingerprint duration is returned as zero (and generally handle HTTP errors properly given behaviour of AcoustId API)
- Fix track grouping service when one album is in a subdirectory of another
Also adds a test for Artist names that are similar to `VA` but are not various artists.  Improves `IdentificationService` test framework so it can use filename matching and fingerprint results supplied in logs.

Fixed: Extra tests and fixes for new track parser

---

src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

NO
After #580 when track naming is disabled it attempts to use the newly set `SceneName`.  But this is the same for each track, so only a single track will import and the rest fails.
This change forces `FileNameBulider` to always use the original file name, not the `SceneName`, when track naming is disabled

Fix: Don't use scene name for tracks when track naming disabled

---

frontend/src/Artist/Details/ArtistDetailsSeason.js
frontend/src/Artist/Details/ArtistDetailsSeasonConnector.js
frontend/src/Settings/UI/UISettings.css
frontend/src/Settings/UI/UISettings.js
src/Lidarr.Api.V1/Config/UiConfigResource.cs
src/NzbDrone.Core/Configuration/ConfigService.cs
src/NzbDrone.Core/Configuration/IConfigService.cs

NO
Add some checkboxes to UI settings to specify which (if any) release types should be expanded by  default.
* fixes #567

Add options to expand album types by default

---

src/NzbDrone.Core/HealthCheck/Checks/FpcalcCheck.cs
src/NzbDrone.Core/Parser/FingerprintingService.cs

NO
Relax fpcalc health check to the version in the LSIO container, at least until they update.  Add caching to fingerprint calculation to speed up re-calculation in Manual Import.

Fixed: Cache fingerprints and relax fpcalc health check

---

src/NzbDrone.Common/Instrumentation/Sentry/SentryCleanser.cs
src/NzbDrone.Common/NzbDrone.Common.csproj
src/NzbDrone.Common/packages.config

NO
Fix mismatched sentry packages preventing app starting on windows.
Also fix `ShortenPath` when compiled on one OS and run on another.

Fixed: Sentry version mismatch

---

.travis.yml
appveyor-package.sh
appveyor.yml
build.sh
frontend/gulp/copy.js
frontend/gulp/helpers/paths.js
package.json
test.sh
yarn.lock

NO
Add Appveyor Linux builds and fix building UI on Linux

Appveyor linux builds

---

src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/GetAlbumsFixture.cs
src/NzbDrone.Core/HealthCheck/Checks/FpcalcCheck.cs
src/NzbDrone.Core/Parser/ParsingService.cs

NO
- Remove unused function from `ParsingService` (following importer rewrite)
- Fix `NullReferenceException` in `GetAlbums`
- Make fpcalc check strict again now that the LSIO docker has updated to bionic
- Strip trailing `.` from exception messages in Sentry to try to get events to group across platforms

Various small fixes

---

src/NzbDrone.Core/Datastore/Migration/028_clean_artistmetadata_table.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

YES
It appears some users have broken databases because they are missing the artist metadata entries corresponding to some artists.
I believe this happened because we had an over-eager housekeeper briefly, fixed in 6723f32abb1e6faf7cba6ae32c3e3a9f6c45b581.
This does a one-off cleanup (with a migration) to remove any Artists/Albums/Tracks linked to this metadata entry, and also any AlbumReleases/Albums/Tracks/Trackfiles linked to now missing items.
In my testing this recovers the database and any the missing artists can be successfully re-imported.

Partially recover databases for users affected by bad 023 migration

---

src/NzbDrone.Core.Test/Download/CompletedDownloadServiceFixture.cs
src/NzbDrone.Core.Test/MusicTests/AlbumRepositoryTests/AlbumRepositoryFixture.cs
src/NzbDrone.Core.Test/MusicTests/ArtistRepositoryTests/ArtistRepositoryFixture.cs
src/NzbDrone.Core/Download/CompletedDownloadService.cs
src/NzbDrone.Core/Music/AlbumRepository.cs
src/NzbDrone.Core/Music/ArtistRepository.cs

NO
- Fix NRE in CompletedDownloadService now we track even if `RemoteAlbum` is `null`
- Remove some `SingleOrDefault`s that throw if we have multiple artists/albums with the same name

Some minor fixes

---

src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs

NO
Filter another type of event from sentry that can occur when a user has incorrect permissions and creates a bootloop.

Fixed: Filter TinyIoC.TinyIoCResolutionException from Sentry

---

src/Lidarr.Api.V1/Artist/ArtistModule.cs
src/NzbDrone.Core/Music/AlbumService.cs

NO
Make sure artist stats get invalidate when an album monitored or unmonitored and push the updated stats to the frontend.

Fixed: Make artist stats update when album (un)monitored

---

src/Lidarr.Api.V1/History/HistoryModule.cs
src/NzbDrone.Core.Test/DecisionEngineTests/AlreadyImportedSpecificationFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/DecisionEngine/Specifications/AlreadyImportedSpecification.cs
src/NzbDrone.Core/History/HistoryRepository.cs
src/NzbDrone.Core/History/HistoryService.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

NO
Prevent releases with same hash or name as one that has already been imported from being re-downloaded.

New: Already Imported Decision Specification

---

src/NzbDrone.Common.Test/InstrumentationTests/SentryTargetFixture.cs
src/NzbDrone.Common.Test/NzbDrone.Common.Test.csproj
src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs

NO
- Fixes 6548f4b1b7bc1bd094f8e3d5a52c7f46b2cc5ff4 (need only class name, not the full name)
- Add tests for `IsSentryMessage`
- Turn on filtering on initialisation to make sure any events thrown before re-configuring logging are filtered.

Fixed: Actually filter TinyIoC errors from sentry and add tests

---

src/NzbDrone.Core.Test/MusicTests/AddAlbumFixture.cs
src/NzbDrone.Core.Test/MusicTests/RefreshAlbumServiceFixture.cs
src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
src/NzbDrone.Core/Music/AddAlbumService.cs
src/NzbDrone.Core/Music/AlbumService.cs
src/NzbDrone.Core/Music/RefreshAlbumService.cs

NO
- Fix unique `ForeignReleaseId` constraint violation when adding a new album which incorporates releases from another album
- Fix possibility of ending up with multiple monitored releases when a monitored release is moved from one album to another which already has a monitored release.

Fixed: Don't attempt to insert duplicate ids or monitor multiple releases

---

src/NzbDrone.Core.Test/MediaFiles/MediaFileRepositoryFixture.cs
src/NzbDrone.Core/MediaFiles/MediaFileRepository.cs

NO
`GetFilesByArtist` and `GetFilesWithRelativePath` were ignoring the `Monitored` flag.  This means that e.g. a file is filtered by `FilterExistingFiles` even if it is mapped against a release that is not currently monitored and so is not visible in the UI.
This was introduced in #592.

Fixed: MediaFileRepository was ignoring AlbumRelease monitored flag

---

appveyor-package.sh
frontend/src/Store/Middleware/createSentryMiddleware.js
src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs
src/NzbDrone.Core/Instrumentation/ReconfigureLogging.cs
src/NzbDrone.Core/Instrumentation/ReconfigureSentry.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

NO
Set sentry environment to be the release update branch (i.e. nightly/develop/master).  Also add details of sqlite version and database migration to sentry events.
I think this would make commit tracking sensible as releases are intermittently pushed to develop.  It would also make it easy to view all events from nightly across nightly versions in the Sentry GUI.
The current setting of `Environment` as `production`/`development` is redundant because we have a separate `dsn` for the standard and development sentry projects, so `production` events always end up in `lidarr` and `development` events always end up in `lidarr-development` regardless of the value of `Environment`
After this change, we will still have all `development` events in `lidarr-development` (due to the different dsn). …

Set sentry environment to be develop/nightly based on config file

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV1.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentTorrent.cs

NO
- Detecting if qbittorrent seeding time limit has been reached
- Don't skip magnet links with included trackers if dht is disabled.
Fixes #697

Fixed: qBittorrent Fixes for Seed Limits and Magnet links

---

src/NzbDrone.Core/Notifications/Slack/Slack.cs

NO
message.Album is null at the moment

Fixed: Slack AlbumImportFailed notification

---

src/NzbDrone.Core.Test/HealthCheck/Checks/RemotePathMappingCheckFixture.cs
src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs

NO
Fixes various sentry errors in new health check.
- Explicitly deal with case where path is invalid and suggest a missing path mapping / bad download client settings for local clients
- Swallow `DownloadClientUnavailable` - these are dealt with separately by the download client check.
The diff is a bit hard to follow, essentially just wrapped the download client access in a try/catch and add the two blocks based on `IsPathValid`.
* Fixes LIDARR-1YZ
* Fixes LIDARR-1Z0
* Fixes LIDARR-1YY
* Fixes LIDARR-1YX
* Fixes LIDARR-1YW

Fix health check errors

---

src/Lidarr.Api.V1/Indexers/ReleaseModule.cs
src/Lidarr.Api.V1/Indexers/ReleasePushModule.cs
src/Lidarr.Api.V1/Indexers/ReleaseResource.cs

NO
Actually use validation for release push, standard PostValidatiors don’t work given we are initiating the endpoint direct with Nancy instead of using our RestModule. 
Fix error and log if release doesn’t get parsed by decision maker
* Fixes #707 
* Fixes LIDARR-1W4

Fixed: ReleasePush Validation and Error on Parse

---

src/NzbDrone.Core/Download/CompletedDownloadService.cs
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs

NO
Prevent tracked downloads from being processed if `RemoteAlbum` is null.  Corrects the fix from 15425a45a
* Fixes LIDARR-1V4

Fixed: Don't process tracked download if RemoteAlbum is null

---

frontend/src/Settings/General/GeneralSettings.js
frontend/src/Settings/General/GeneralSettingsConnector.js
frontend/src/Settings/General/UpdateSettings.js
frontend/src/System/Status/About/About.js
frontend/src/System/Updates/Updates.js
frontend/src/System/Updates/UpdatesConnector.js
src/Lidarr.Api.V1/System/SystemModule.cs
src/NzbDrone.Common/EnvironmentInfo/OsInfo.cs
src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs
src/NzbDrone.Core.Test/HealthCheck/Checks/RemotePathMappingCheckFixture.cs
src/NzbDrone.Core.Test/UpdateTests/UpdateServiceFixture.cs
src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs
src/NzbDrone.Core/Update/InstallUpdateService.cs

NO
Prevent Lidarr from updating inside a docker container.  Also note that docker is being used in the about page and sentry context.
* Fixes #628

Fixed: Disable update for docker containers

---

src/NzbDrone.Core.Test/UpdateTests/UpdateServiceFixture.cs
src/NzbDrone.Core/Update/InstallUpdateService.cs

NO
Don't throw errors if docker update attempt is stopped

Fixed: Don't throw error on Docker Update Attempt

---

frontend/src/Store/Middleware/createSentryMiddleware.js
src/Lidarr.Http/Frontend/InitializeJsModule.cs

NO
Frontend errors have no associated user, this will use the same AnonToken from server side to attach to UI events
Example event:
https://sentry.io/organizations/lidarr/issues/974992887/

New: Associate same AnonToken with Sentry UI instance

---

src/NzbDrone.Core.Test/HealthCheck/Checks/RemotePathMappingCheckFixture.cs
src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs

NO
Ignore `DownloadClientAuthenticationException` and `DownloadClientException` as well as `DownloadClientUnavailableException` (i.e. don't log to sentry)

Fixed: RemotePathMappingCheck should ignore all download client exceptions

---

build.sh

NO
Modern versions of mono produce PDBs and not MDBs; if these are generated they should not be removed.
`Lidarr.Core.dll.config` no longer exists so don't try to copy to test directory.

Keep mono PDBs, don't try to copy missing dll.config

---

frontend/src/Album/Details/AlbumDetailsPageConnector.js
src/Lidarr.Api.V1/Albums/AlbumLookupModule.cs
src/Lidarr.Api.V1/Albums/AlbumModule.cs
src/Lidarr.Api.V1/Artist/ArtistLookupModule.cs
src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs

NO
- Make the Album/Artists lookup endpoints show an error if they fail instead of silently responding `500`
- Reinstate `foreignArtistId` for album lookup on a specific album (i.e. queried with foreign ID)
* Fixes #733 
* Fixes #731

Fixed: Album Lookup API

---

src/NzbDrone.Core.Test/DecisionEngineTests/AlreadyImportedSpecificationFixture.cs
src/NzbDrone.Core/DecisionEngine/Specifications/AlreadyImportedSpecification.cs

NO
Check for null infoHash and prevent error if so
Fixes #741 
Fixes LIDARR-1Y5
*

Fixed: Nullref due to InfoHash on AlreadyImportedSpec

---

src/NzbDrone.Core.Test/Datastore/Migration/023_add_release_groups_etcFixture.cs
src/NzbDrone.Core/Datastore/Migration/023_add_release_groups_etc.cs

NO
Ensure Migration 23 sets Track.ArtistMetadataId from Album

Fixed: Migration 23 doesn't set Track.ArtistMetadataId

---

src/NzbDrone.Core/MediaFiles/TrackImport/Manual/ManualImportItem.cs

NO
Make sure `x.tracks` is defined before trying to access length.
Fixes error in track selection in manual import.
Fixes Sentry LIDARR-UI-1GC

Fixed: Error selecting tracks in manual import dialog

---

src/NzbDrone.Core.Test/MusicTests/AddAlbumFixture.cs
src/NzbDrone.Core.Test/MusicTests/RefreshAlbumServiceFixture.cs
src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
src/NzbDrone.Core/Music/AddAlbumService.cs
src/NzbDrone.Core/Music/RefreshAlbumService.cs
src/NzbDrone.Core/Music/RefreshArtistService.cs

NO
Only mark artist as refreshed if track refresh successful. Also skip albums and releases with no valid tracks.

Fixed: Skip albums and releases with no valid tracks

---

frontend/src/Album/Details/TrackRow.css
frontend/src/Settings/MediaManagement/Naming/NamingModal.js
frontend/src/TrackFile/MediaInfo.js
src/Lidarr.Api.V1/TrackFiles/MediaInfoResource.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
src/NzbDrone.Core/MediaFiles/MediaInfoFormatter.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

NO
- Add naming token for AudioBitRate
- Return blank for AudioBits when = to 0
- Add tests for MediaInfo Tokens
- Show Bits and SampleRate in UI Track table
#758 partial

New: AudioBitRate Naming Token

---

src/NzbDrone.Core/Music/ArtistMetadata.cs
src/NzbDrone.Core/Music/RefreshAlbumService.cs

NO
If ArtistMetadata or Album Overview or Images are blank during refresh, stay with whats already in the db. This will prevent Lidarr user experience decline if/when metadata is being rated limited by providers. 
Reference #761

New: Don't overwrite Images/Overviews if new is blank

---

src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs

NO
Fixes issue with health check reported on discord.  Was adding a bonus `.` into the path.

Remove rogue . from transmission output directory

---

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/QualityParser.cs

Don't try to match a null codec name

---

src/NzbDrone.Common/Exceptions/LidarrStartupException.cs
src/NzbDrone.Host/AccessControl/UrlAclAdapter.cs

NO
Throw LidarrStartupException if HTTP and HTTPS port are same and `EnableSSL` is `True`

Fixed: Throw Startup Exception on same port for SSL

---

src/NzbDrone.Core.Test/MetadataSource/MetadataRequestBuilderFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/ImportLists/LidarrLists/LidarrLists.cs
src/NzbDrone.Core/ImportLists/LidarrLists/LidarrListsRequestGenerator.cs
src/NzbDrone.Core/ImportLists/LidarrLists/LidarrListsSettings.cs
src/NzbDrone.Core/MetadataSource/IMetadataRequestBuilder.cs
src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

NO
- Use the metadata server default or the custom server defined in settings for the Lidarr Lists.

Fixed: Lidarr Lists use correct metadata server

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/TorrentDownloadStationFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/UsenetDownloadStationFixture.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs

NO
Map DSM shared folder to proper path in status for use in root path heath check.
Tested by gouty on discord.
*

Fixed: Map dsm shared folder to full path in status

---

frontend/src/Activity/Queue/Queue.js
frontend/src/Activity/Queue/QueueConnector.js
frontend/src/Activity/Queue/QueueRow.js
frontend/src/Activity/Queue/QueueRowConnector.js
frontend/src/Activity/Queue/RemoveQueueItemModal.js
frontend/src/Activity/Queue/RemoveQueueItemsModal.js
frontend/src/Store/Actions/queueActions.js
src/Lidarr.Api.V1/Queue/QueueActionModule.cs
src/NzbDrone.Core.Test/Download/RedownloadFailedDownloadServiceFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Download/DownloadFailedEvent.cs
src/NzbDrone.Core/Download/FailedDownloadService.cs
src/NzbDrone.Core/Download/RedownloadFailedDownloadService.cs

NO
When trying to remove a failed/not matching download from queue with blacklisting, it should be possible to skip the automatic redownload as it would try to find another release which might be unwanted.
Adds tests to #616

Add: option to skip automatic redownload when removing from queue

---

src/NzbDrone.Core/Parser/FingerprintingService.cs

NO
Try to prevent `cmd.exe` windows popping up on windows every time `fpcalc` runs

Fixed: Don't show cmd.exe window when fpcalc runs

---

src/NzbDrone.Core.Test/MediaFiles/MediaFileRepositoryFixture.cs
src/NzbDrone.Core/MediaFiles/MediaFileRepository.cs
src/NzbDrone.Core/MediaFiles/MediaFileService.cs

NO
GetFilesByAlbum performs a join on the album releases under the hood,
which won't be populated once the album is deleted.  Fix by providing
a special delete method which omits the join and just looks at albumId.

Fixed: Correctly delete trackfiles on AlbumDeletedEvent

---

src/NzbDrone.Api.Test/NzbDrone.Api.Test.csproj
src/NzbDrone.App.Test/NzbDrone.Host.Test.csproj
src/NzbDrone.Common.Test/NzbDrone.Common.Test.csproj
src/NzbDrone.Core.Test/Framework/CoreTest.cs
src/NzbDrone.Core.Test/MediaFiles/DiskScanServiceTests/ScanFixture.cs
src/NzbDrone.Core.Test/MediaFiles/TrackImport/ImportDecisionMakerFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Integration.Test/NzbDrone.Integration.Test.csproj
src/NzbDrone.Mono.Test/NzbDrone.Mono.Test.csproj
src/NzbDrone.Test.Common/NzbDrone.Test.Common.csproj
src/NzbDrone.Update.Test/NzbDrone.Update.Test.csproj

NO
- Update Moq (previous version was from 2011!).  One of the fixes is required for tests in #838.  
- Fix `UseRealHttp()` for metadata requests following addition of `MetadataRequestBuilder

New: Bump Moq to 4.12

---

src/NzbDrone.Core.Test/Messaging/Commands/CommandQueueFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/ImportLists/ImportListSyncCommand.cs
src/NzbDrone.Core/Messaging/Commands/Command.cs
src/NzbDrone.Core/Messaging/Commands/CommandQueue.cs

NO
Allow setting of `isTypeExclusive` for commands so that only one command of that type runs in parallel
Import List adding duplicate artists
*

New: Don't Execute Certain Command Types In Parallel

---

src/NzbDrone.Core.Test/Datastore/Migration/031_add_artistmetadataid_constraintFixture.cs
src/NzbDrone.Core.Test/Messaging/Commands/CommandQueueFixture.cs
src/NzbDrone.Core.Test/MusicTests/ArtistRepositoryTests/ArtistRepositoryFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Datastore/Migration/031_add_artistmetadataid_constraint.cs
src/NzbDrone.Core/Messaging/Commands/CommandQueue.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

YES (31)
When we redid the database structure in 23, we allowed two artists to point to the same artist metadata entry and so same foreign artist id.  This should not be allowed.  This adds a unique constraint on `ArtistMetadataId` and removes any duplicate artists, keeping the one with the lowest `Id` (i.e. the first one created).
* Fixes Sentry 21C
* Fixes Sentry 22D

Fixed: Prevent two Artists pointing to same ArtistMetadata

---

src/NzbDrone.Core.Test/MediaFiles/AudioTagServiceFixture.cs
src/NzbDrone.Core/MediaFiles/AudioTagService.cs
src/NzbDrone.Core/MediaFiles/TrackImport/Manual/ManualImportService.cs

NO
Now that we only scan changed files, it's important to make sure sizes/last modified are populated and kept up to date if we make a deliberate change.
This PR fixes two issues:
- Manual import wasn't setting modified or size when importing, so files would get rescanned on next scan
- Tag sync would change modified/size on disk but this wasn't noted in the database so files would be rescanned on next scan

Fixed: Make sure modified/size set by manual import and tag sync

---

src/NzbDrone.Core.Test/Download/TrackedDownloads/TrackedDownloadServiceFixture.cs
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs

NO
Currently the tracked download service cache references to albums that match to tracked downloads. If albums are deleted (via metadata change, or other) those references create errors during queue lookup (#707). Thus we need to update tracked downloads to remove deleted album reference when an album is deleted. 
@ta264 not sure if this is the best way to go about this, but it seems to work for me?
Fixes #707 (For Albums)
Fixes LIDARR-1X1
*

Fixed: Tracked Download Cache Keeps Deleted Albums

---

src/NzbDrone.Core.Test/MediaFiles/TrackImport/Identification/IdentificationServiceFixture.cs
src/NzbDrone.Core.Test/MusicTests/ArtistMetadataRepositoryTests/ArtistMetadataRepositoryFixture.cs
src/NzbDrone.Core.Test/MusicTests/RefreshAlbumServiceFixture.cs
src/NzbDrone.Core.Test/MusicTests/RefreshArtistServiceFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Music/AddArtistService.cs
src/NzbDrone.Core/Music/ArtistMetadataService.cs
src/NzbDrone.Core/Music/RefreshAlbumReleaseService.cs
src/NzbDrone.Core/Music/RefreshAlbumService.cs
src/NzbDrone.Core/Music/RefreshArtistService.cs
src/NzbDrone.Core/Music/RefreshEntityServiceBase.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Parser/FingerprintingService.cs

NO
#838 introduced two issues:
1. Removing an artist and adding again caused an error.
1. Media covers weren't refreshing.
The first is fixed by introducing an `ArtistMetadataService` to prevent using inappropriate methods from `BasicRepository` (needed to use `UpsertMany` and not `Upsert`).  Also added tests for ArtistMetadataRepository to make sure that works properly.
The second is fixed by `virtual -> override`.
Also, add a timeout to AcoustID API - it was hanging earlier making tests really slow to run.

Some fixes from #838

---

src/NzbDrone.Common/Http/HttpResponse.cs
src/NzbDrone.Core.Test/MediaCoverTests/CoverExistsSpecificationFixture.cs
src/NzbDrone.Core.Test/MediaCoverTests/MediaCoverServiceFixture.cs
src/NzbDrone.Core/MediaCover/CoverAlreadyExistsSpecification.cs
src/NzbDrone.Core/MediaCover/MediaCoverService.cs

NO
This implements 2 things:
- Follow 307 Temp Redirects when we allow redirect in httpClient
- Look for ContentLength Headers as a backup if Last Modified does not exist. (maybe we want to change this to check if the last modify check fails?)
* Fixes #850

Fix mediacover existing check

---

frontend/src/Settings/ImportLists/ImportLists/EditImportListModalContent.css
frontend/src/Settings/ImportLists/ImportLists/EditImportListModalContent.js
frontend/src/Store/Actions/Settings/importLists.js
src/Lidarr.Api.V1/ImportLists/ImportListResource.cs
src/NzbDrone.Core.Test/ImportListTests/ImportListSyncServiceFixture.cs
src/NzbDrone.Core/ImportLists/ImportListDefinition.cs
src/NzbDrone.Core/ImportLists/ImportListSyncService.cs

NO
Currently when an import list returns albums (instead of artists) and "monitor" is selected in the import list, only the albums actually in the import list are monitored.  Other albums that match the metadata profile for the same artist are not monitored.
As requested by a user on Discord (and seems like a good idea to me) this allows you to choose whether to monitor just the album in the import list or every album by an artist appearing on the list.

New: Allow monitoring all albums for import list artist

---

frontend/src/Settings/MediaManagement/MediaManagement.js
src/Lidarr.Api.V1/Config/MediaManagementConfigResource.cs
src/NzbDrone.Core.Test/DecisionEngineTests/PrioritizeDownloadDecisionFixture.cs
src/NzbDrone.Core.Test/DecisionEngineTests/RepackSpecificationFixture.cs
src/NzbDrone.Core.Test/DecisionEngineTests/RssSync/ProperSpecificationFixture.cs
src/NzbDrone.Core.Test/DecisionEngineTests/UpgradeSpecificationFixture.cs
src/NzbDrone.Core.Test/MediaFiles/TrackImport/Specifications/UpgradeSpecificationFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Configuration/ConfigService.cs
src/NzbDrone.Core/Configuration/IConfigService.cs
src/NzbDrone.Core/Datastore/Migration/033_download_propers_config.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionPriorizationService.cs
src/NzbDrone.Core/DecisionEngine/Specifications/RepackSpecification.cs
src/NzbDrone.Core/DecisionEngine/Specifications/RssSync/ProperSpecification.cs
src/NzbDrone.Core/DecisionEngine/Specifications/UpgradableSpecification.cs
src/NzbDrone.Core/MediaFiles/TrackImport/Specifications/UpgradeSpecification.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Parser/QualityParser.cs
src/NzbDrone.Core/Qualities/ProperDownloadTypes.cs
src/NzbDrone.Core/Qualities/Revision.cs

NO
Repack releases should only be grabbed for same release group. This PR enforces that repack releases will only be grabbed if the release group is the same as the current album on file. As written all files for a specific album have to be from the release group, if there are mixed groups the release is rejected.

Fixed: Correctly handle Repack Releases

---

src/NzbDrone.Core.Test/MediaCoverTests/MediaCoverServiceFixture.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Roksbox/RoksboxMetadata.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
src/NzbDrone.Core/MediaCover/MediaCover.cs
src/NzbDrone.Core/MediaCover/MediaCoverService.cs

NO
- Maintain original image format when downloading/resizing - don't force to `.jpg`
- Fix KODI album art names (`folder.jpg` and `discart.jpg`)
* Fixes #872

Fixed: Don't force images to JPG and fix Kodi album art filenames

---

src/NzbDrone.Core/Music/AlbumService.cs
src/NzbDrone.Core/Parser/ParsingService.cs

NO
The parser was giving the artist id not the artist metadata id.  It should definitely be using the metadata id: https://github.com/lidarr/Lidarr/blob/9ccef35f8f20746e0fee50564f7686c984372549/src/NzbDrone.Core/Music/AlbumService.cs#L102

Fixed: Use correct ID to search for Albums

---

src/NzbDrone.Core.Test/MediaCoverTests/MediaCoverServiceFixture.cs
src/NzbDrone.Core/MediaCover/MediaCover.cs
src/NzbDrone.Core/MediaFiles/AudioTagService.cs

NO
On import the album release is adjusted, which triggers an AlbumEditedEvent which in turn converts media cover urls to local urls.  The addition of ?lastWrite=xxx broke the calculation of extensions from the URL.  To fix, only set the extension and don't update the extension if url is changed.
* Fixes issue reported on discord

Fixed: Embedding album art on import

---

frontend/src/Activity/Blacklist/BlacklistRow.js
frontend/src/Activity/History/HistoryRow.js
frontend/src/AlbumStudio/AlbumStudio.js
frontend/src/Artist/Editor/ArtistEditor.js
frontend/src/Artist/Index/ArtistIndex.css
frontend/src/Artist/Index/ArtistIndex.js
frontend/src/Calendar/CalendarPage.css
frontend/src/Calendar/CalendarPage.js
frontend/src/Calendar/CalendarPageConnector.js
frontend/src/Components/Page/PageConnector.js
frontend/src/Store/Selectors/createArtistCountSelector.js
frontend/src/Wanted/CutoffUnmet/CutoffUnmetRow.js
src/Lidarr.Api.V1/Artist/ArtistModule.cs
src/Lidarr.Api.V1/Artist/ArtistResource.cs
src/NzbDrone.Core.Test/MusicTests/AlbumRepositoryTests/AlbumRepositoryFixture.cs
src/NzbDrone.Core/Datastore/BasicRepository.cs
src/NzbDrone.Core/Music/AlbumRepository.cs
src/NzbDrone.Core/Music/AlbumService.cs

NO
Speed up the artist endpoint.  `All()` was skipping the metadata join, so we were querying metadata separately per artist and also the albums separately per artist.
Also allow the UI to display before the artists have loaded from the API (and display errors appropriately if they fail to load).  For people where an in progress scan prevents the UI loading, this at least lets them get to settings to disable scan.

Fixed: Faster artist endpoint

---

src/NzbDrone.Core/MediaFiles/AudioTag.cs

NO
For MP3's, the official separator is " / " and this also works for FLAC.  Change the UI separator to match the way the tags are written.

Fixed: Change UI Genre Tag Separator from ", " to " / "

---

frontend/src/Album/Details/AlbumDetailsPageConnector.js
frontend/src/Artist/Details/ArtistDetails.css
frontend/src/Artist/Details/ArtistDetailsPageConnector.js

NO
Fix up #874 - check that artist store is loaded when loading album/artist details page. 
* Fixes temporary 404 on refreshing artist details page
* Fixes error and failed render refreshing album details page
* Fixes #631

Fixed: Refreshing artist/album details shows 404 until store loads

---

src/NzbDrone.Core.Test/Lidarr.Core.Test.csproj
src/NzbDrone.Core.Test/MusicTests/EntityFixture.cs
src/NzbDrone.Core.Test/MusicTests/RefreshAlbumReleaseServiceFixture.cs
src/NzbDrone.Core.Test/MusicTests/RefreshAlbumServiceFixture.cs
src/NzbDrone.Core.Test/MusicTests/RefreshTrackServiceFixture.cs
src/NzbDrone.Core/Lidarr.Core.csproj
src/NzbDrone.Core/MediaCover/MediaCover.cs
src/NzbDrone.Core/Music/Album.cs
src/NzbDrone.Core/Music/Artist.cs
src/NzbDrone.Core/Music/ArtistMetadata.cs
src/NzbDrone.Core/Music/ArtistMetadataRepository.cs
src/NzbDrone.Core/Music/Entity.cs
src/NzbDrone.Core/Music/Links.cs
src/NzbDrone.Core/Music/Medium.cs
src/NzbDrone.Core/Music/Member.cs
src/NzbDrone.Core/Music/Ratings.cs
src/NzbDrone.Core/Music/RefreshAlbumReleaseService.cs
src/NzbDrone.Core/Music/RefreshAlbumService.cs
src/NzbDrone.Core/Music/RefreshArtistService.cs
src/NzbDrone.Core/Music/RefreshEntityServiceBase.cs
src/NzbDrone.Core/Music/RefreshTrackService.cs
src/NzbDrone.Core/Music/Release.cs
src/NzbDrone.Core/Music/Track.cs

NO
Simplify entity equality code and enforce db/metadata field split
Use a nuget package to remove boilerplate code that needs careful
update when adding/removing fields.  Add tests to enforce that all
fields are allocated to 'UseMetadataFrom' or 'UseDbFieldsFrom' to make
metadata refresh more foolproof.
* Fixes #883 
* Fixes #887 
* Fixes Sentry LIDARR-3GT
* Fixes Sentry LIDARR-3H0

Fixed: Null reference exception on refresh when tracks updated

---

src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs

NO
Fixes a Null Ref in UpdateAlbumCache
Fixes #886

Fixed: Null Ref on Album Cache Update in TrackedDownloadService.cs

---

src/NzbDrone.Core.Test/MediaFiles/AudioTagServiceFixture.cs
src/NzbDrone.Core/MediaFiles/AudioTagService.cs

NO
Fixes NRE if album has a media omitted so index in the list isn't the same as the medium number.
* Fixes #958

Fixed: NRE when tagging an album with omitted media

---

src/NzbDrone.Core.Test/ImportListTests/Spotify/SpotifyFollowedArtistsFixture.cs
src/NzbDrone.Core.Test/ImportListTests/Spotify/SpotifyPlaylistFixture.cs
src/NzbDrone.Core.Test/ImportListTests/Spotify/SpotifySavedAlbumsFixture.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifyFollowedArtists.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifyImportListBase.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifyPlaylist.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifyProxy.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifySavedAlbums.cs

NO
Rework spotify import lists to use a `ISpotifyProxy` interface so we can test.  Add tests
* Fixes #957

Fixed: NRE importing Spotify saved albums / followed artists

---

src/NzbDrone.Common.Test/DiskTests/DiskProviderFixtureBase.cs
src/NzbDrone.Common/Disk/DiskProviderBase.cs

NO
`RemoveEmptySubfolders` fails with nested empty subfolders.  It needs to search for directories recursively and delete empty children before trying to delete empty parents.
* Fixes Sentry Lidarr-1qj
* Fixes Sentry Lidarr-1qz
* Fixes Sentry Lidarr-24a
* Fixes Sentry Lidarr-3T8
* Fixes Sentry Lidarr-25R

Fixed: Directory not empty exception deleting nested empty subdirectories

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
Clean the spotify refresh_token from logs

Fixed: Clean Spotify Refresh Token from Logs

---

src/NzbDrone.Core/Music/ReleaseStatus.cs

NO
Fixes name of pseudo release to match metadata server/mb naming
Fixes #987

Fixed: Pseudo Release Incorrect Enum Name

---

src/NzbDrone.Core.Test/MusicTests/ArtistRepositoryTests/ArtistRepositoryFixture.cs
src/NzbDrone.Core/ImportLists/ImportListSyncService.cs
src/NzbDrone.Core/Music/ArtistRepository.cs

NO
When using FindById, check oldIds column as well. This ensures we don't accidentally try and add an artist from a list if the list gives an old Id.
Also, break and log to next report in list processing if artist is existing. Save some processing for now until album add is added
Fixes #970 
Fixes LIDARR-3FY
*

Fixed: Artist FindById Should Find OldIds

---

src/NzbDrone.Core.Test/ImportListTests/Spotify/SpotifyFollowedArtistsFixture.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifyFollowedArtists.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifyProxy.cs

NO
Fix the Spotify followed artist import list so that it imports more than 20 artists.  The paging was set up incorrectly for following artists, making the wrong API call.  Tested by setting limit to 1 and verifying all artists appear.
Page size increased to 50 (the max) to minimize number of pages required.
* User on discord reported followed artists limited to 20 (the default page size).

Fixed: Correctly page through Spotify followed artists

---

src/NzbDrone.Core.Test/MediaFiles/MediaFileRepositoryFixture.cs
src/NzbDrone.Core/MediaFiles/MediaFileRepository.cs

NO
When searching for /test/path it was returning files in /test/path2.
Fix by making sure to search for /test/path/
* Issue reported on discord

Fixed: Prevent GetFilesByBasePath matching partial paths

---

src/NzbDrone.Core.Test/ImportListTests/ImportListSyncServiceFixture.cs
src/NzbDrone.Core.Test/ImportListTests/Spotify/SpotifyMappingFixture.cs
src/NzbDrone.Core/ImportLists/ImportListSyncService.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifyFollowedArtists.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifyImportListBase.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifyImportListItemInfo.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifyMap.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifyPlaylist.cs
src/NzbDrone.Core/ImportLists/Spotify/SpotifySavedAlbums.cs

NO
The metadata server has a new endpoint for the mapping from Spotify to musicbrainz.  If no mapping already found, it does a search, takes the best result and caches this for next time.
This commit edits the Spotify import lists to use the new endpoint instead of letting `ImportListSyncService` do a search.

New: Cache spotify -> musicbrainz mapping

---

frontend/src/Components/Form/MetadataProfileSelectInputConnector.js
frontend/src/Components/Form/QualityProfileSelectInputConnector.js
frontend/src/InteractiveImport/Artist/SelectArtistModalContentConnector.js
frontend/src/Settings/DownloadClients/DownloadClients/DownloadClients.js
frontend/src/Settings/DownloadClients/DownloadClients/DownloadClientsConnector.js
frontend/src/Settings/ImportLists/ImportLists/ImportLists.js
frontend/src/Settings/ImportLists/ImportLists/ImportListsConnector.js
frontend/src/Settings/Indexers/Indexers/Indexers.js
frontend/src/Settings/Indexers/Indexers/IndexersConnector.js
frontend/src/Settings/Metadata/Metadata/Metadatas.js
frontend/src/Settings/Metadata/Metadata/MetadatasConnector.js
frontend/src/Settings/Notifications/Notifications/Notifications.js
frontend/src/Settings/Notifications/Notifications/NotificationsConnector.js
frontend/src/Settings/Profiles/Quality/QualityProfiles.js
frontend/src/Settings/Profiles/Quality/QualityProfilesConnector.js
frontend/src/Store/Selectors/createSortedSectionSelector.js

NO
Fixes the UI issues that arise from sorting mutating state which means the `itemMap` doesn't match up with `items`.

Fixed: Editing provider/profile settings appearing to affect wrong item

---

src/NzbDrone.Core.Test/Download/CompletedDownloadServiceFixture.cs
src/NzbDrone.Core/Download/CompletedDownloadService.cs

NO
Restores Sonarr/Radarr behaviour where a download is retried until the files become available.  Restores compatibility with seedboxes.
The downside is that if the path doesn't exist (e.g. due to a bad/missing remote path mapping) it'll just sit in the queue indefinitely instead of failing with a warning.
- [] Tests
* #945

Fixed: Don't mark downloads as failed if no files found

---

src/NzbDrone.Core.Test/ImportListTests/ImportListSyncServiceFixture.cs
src/NzbDrone.Core/ImportLists/ImportListSyncService.cs
src/NzbDrone.Core/Music/Events/ArtistsImportedEvent.cs
src/NzbDrone.Core/Music/Handlers/ArtistAddedHandler.cs
src/NzbDrone.Core/Music/Services/AddArtistService.cs
src/NzbDrone.Core/Music/Services/ArtistService.cs

NO
Make sure we only trigger one folder scan when adding multiple artists via a list
* Fixes #1186

Fixed: Don't rescan folders for each artist added via a list

---

src/NuGet.config
src/NzbDrone.Core/Lidarr.Core.csproj

NO
Update taglib to fix opus corruption bug
* Fixes #841

Fixed: Don't corrupt OPUS files when tagging them

---

src/Lidarr.Api.V1/Artist/ArtistModule.cs
src/NzbDrone.Core.Test/MusicTests/AlbumMonitoredServiceTests/AlbumMonitoredServiceFixture.cs
src/NzbDrone.Core.Test/MusicTests/MoveArtistServiceFixture.cs
src/NzbDrone.Core.Test/MusicTests/RefreshArtistServiceFixture.cs
src/NzbDrone.Core/Extras/ExtraService.cs
src/NzbDrone.Core/Extras/Files/ExtraFileManager.cs
src/NzbDrone.Core/Extras/Lyrics/LyricService.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
src/NzbDrone.Core/Extras/Metadata/MetadataService.cs
src/NzbDrone.Core/Extras/Others/OtherExtraService.cs
src/NzbDrone.Core/MediaCover/MediaCoverService.cs
src/NzbDrone.Core/MediaCover/MediaCoversUpdatedEvent.cs
src/NzbDrone.Core/Music/Services/ArtistService.cs
src/NzbDrone.Core/Music/Services/RefreshAlbumService.cs
src/NzbDrone.Core/Music/Services/RefreshArtistService.cs

NO
It was writing the musicbrainz releasegroupid as album id, it should be writing the releaseid
- Closes #1399 
- Closes #1338  
- Closes #1318

Fixed: Write the correct album/releasegroup ids for XBMC/Emby

---

src/NzbDrone.Core/Download/Clients/Flood/Flood.cs
src/NzbDrone.Core/Download/Clients/Flood/FloodProxy.cs
src/NzbDrone.Core/Download/Clients/Flood/FloodSettings.cs
src/NzbDrone.Core/Download/Clients/Flood/Models/AdditionalTags.cs
src/NzbDrone.Core/Download/Clients/Flood/Types/Torrent.cs
src/NzbDrone.Core/Download/Clients/Flood/Types/TorrentContent.cs
src/NzbDrone.Core/Download/Clients/Flood/Types/TorrentListSummary.cs

NO
Adds support for the [Flood](https://flood.js.org/) download client. 
Based on jesec's additions to Sonarr [here](https://github.com/Sonarr/Sonarr/pull/4159) and Radarr [here](https://github.com/Radarr/Radarr/pull/5552), but with Lidarr flavor.
* #1922 
* #1923

Add Support for Flood

---

frontend/src/Settings/MediaManagement/Naming/NamingModal.js
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs
src/NzbDrone.Core/Organizer/FileNameSampleService.cs

NO
Adds a new `{Track ArtistName}` token that contains the track's artist name, not the album's artist name. This is primarily useful with "Various Artists" albums.
I originally tried calling it `{Track Artist Name}` but the `TitleRegex` only allows a single space in the token name, so I went with `{Track ArtistName}` instead. Let me know if you'd prefer some other token.
Before:
After:
* Fixes #1791

New: Token for track artist (as opposed to album artist)

---

src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs

NO
Kodi reads the artist name from the `name` field, not the `title` field. See [kodi.wiki](https://kodi.wiki/view/NFO_files/Music#nfo_Tags). I think this was missed when tvshow.nfo was converted to artist.nfo.
It doesn't look like there are any tests for writing metadata. Should I create one for this change?
* N/A

Use name instead of title for XBMC artist.nfo metadata

---

src/NzbDrone.Core/Download/DownloadClientInfo.cs
src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs

NO
Fixes null reference error caused by RuTorrent not providing DownloadClientInfo

Fixed: Root Folder Downloads check giving errors when RuTorrent is used

---

frontend/src/Settings/MediaManagement/MediaManagement.js

NO
In Media Management, there was a checkbox to Unmonitor Deleted Tracks, which was not hooked up to any code. This PR removes that checkbox from the UI to avoid any confusion.

Fixed: Remove checkbox to unmonitor tracks on delete

---

src/Lidarr.Api.V1/Blocklist/BlocklistController.cs
src/Lidarr.Api.V1/Queue/QueueController.cs

NO
Manually removing a release from the Activity screen was not properly adding the release to the Block List when selected. This removes incorrect leftover references of "blacklist" to "blocklist" and resolves the issue.
* Fixes #2521 
* Fixes [AB#2104](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2104)

Fixed: Manual adding to blocklist

---

src/Lidarr.Api.V1/Artist/ArtistController.cs
src/Lidarr.Api.V1/Config/MediaManagementConfigController.cs
src/Lidarr.Api.V1/RootFolders/RootFolderController.cs
src/NzbDrone.Core/Download/Clients/Flood/Flood.cs
src/NzbDrone.Core/Download/Clients/Flood/FloodProxy.cs
src/NzbDrone.Core/Download/Clients/Flood/Types/FloodClientSettings.cs
src/NzbDrone.Core/Music/Utilities/AddArtistValidator.cs
src/NzbDrone.Core/Validation/Paths/ArtistPathValidator.cs
src/NzbDrone.Core/Validation/Paths/RecycleBinValidator.cs
src/NzbDrone.Core/Validation/Paths/RootFolderAncestorValidator.cs

Fixes 1794
(cherry picked from commit fd4fb88ce1efa8f673c74f04cd632a3f607565c4)
NO
Adds validation check for recycling bin folder that is also a root folder.
* Fixes #1794

New: Add Validations for Recycle Bin Folder

---

frontend/src/Components/Form/DownloadClientSelectInputConnector.js
frontend/src/Components/Form/FormInputGroup.js
frontend/src/Helpers/Props/inputTypes.js
frontend/src/Settings/Indexers/Indexers/EditIndexerModalContent.js
src/Lidarr.Api.V1/Indexers/IndexerResource.cs
src/NzbDrone.Core.Test/Download/DownloadClientProviderFixture.cs
src/NzbDrone.Core.Test/Download/DownloadServiceFixture.cs
src/NzbDrone.Core/Datastore/Migration/055_download_client_per_indexer.cs
src/NzbDrone.Core/Download/DownloadClientProvider.cs
src/NzbDrone.Core/Download/DownloadService.cs
src/NzbDrone.Core/Indexers/IndexerDefinition.cs
src/NzbDrone.Core/ThingiProvider/IProviderFactory.cs
src/NzbDrone.Core/ThingiProvider/ProviderFactory.cs

(cherry picked from commit 13aaa20f1bf1448fa804738804205cb16f0d91f9)
YES - 055 (DownloadClientId on Indexers)
Allow user to specify a particular client for an indexer
Basically copied from this sonarr change:
https://github.com/Sonarr/Sonarr/pull/4844
* Closes #2606

New: Link indexer to specific download client

---

src/NzbDrone.Core.Test/Files/Identification/CorruptFile.json
src/NzbDrone.Core.Test/Files/Identification/FilesWithMBIds.json
src/NzbDrone.Core.Test/Files/Identification/FilesWithoutTags.json
src/NzbDrone.Core.Test/Files/Identification/InconsistentTyposInAlbum.json
src/NzbDrone.Core.Test/Files/Identification/PenalizeUnknownMedia.json
src/NzbDrone.Core.Test/Files/Identification/PreferMissingToBadMatch.json
src/NzbDrone.Core.Test/Files/Identification/SucceedWhenManyAlbumsHaveSameTitle.json
src/NzbDrone.Core/Datastore/Migration/060_update_audio_types.cs
src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
src/NzbDrone.Core/Music/Model/SecondaryAlbumType.cs

* Fixes Metadata Profile selector - "Audio drama" missing in "Edit Metadata Profile" (https://musicbrainz.org/doc/Release_Group/Type)

Missing secondary type (Audio drama) added

---

src/Lidarr.Api.V1/Calendar/CalendarFeedController.cs

NO
Adds a `DTEND` tag to the iCal events
Fixes: #3218

fix: add end date to calendar events

---

src/NzbDrone.Core.Test/IndexerSearchTests/SearchDefinitionFixture.cs
src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs

NO
Mostly undoing 1eea545c0a9e2ea871a98f5adcede515055a0d95 d765d1eaeff42a12da294666904a9109031cdf28
Currently `Section80` returns 0 results on RED/OPS, while `Section 80` returns the `Section.80` album.
Same for `Anthology Hey Ho Lets Go` vs `Anthology Hey Ho Let's Go`.

Fixed: Standardize single quotes and allow the neutral apostrophe

---

src/Lidarr.Http/Frontend/Mappers/StaticResourceMapperBase.cs

NO
Serve text files as UTF-8, so as to ensure they are properly decoded by browsers. This fixes issues with log readability.
This is the same fix as Prowlarr/Prowlarr#1372, for Lidarr.

Fixed: Specify UTF-8 when serving text files to avoid incorrect detection by browsers
