src/UI/Artist/Edit/EditArtistView.js
=> Fixes Artist Delete after Previous UI Work

src/UI/AddArtist/SearchResultView.js
NO
Fixes Existing Detection on In Search Results when adding a new artist. Tested and working.
*
=> Fixes Existing Detection In Search Results when adding artist

src/NzbDrone.Common.Test/EnsureTest/PathExtensionFixture.cs, src/NzbDrone.Common.Test/PathExtensionFixture.cs, src/NzbDrone.Common/Extensions/PathExtensions.cs, src/NzbDrone.Update.Test/StartNzbDroneService.cs
NO
Fixes a few path related tests
*
=> Fixes a few PathExtensionFixture Tests

src/NzbDrone.Core/Music/AlbumRepository.cs, src/UI/Cells/AlbumTitleCell.js, src/UI/Wanted/Missing/MissingLayout.js
NO
Fix wanted page query so it only pulls albums with missing tracks, Correct Album header on wanted page, Implement albumTitleCell to allow click on album.
*
=> Tweak Wanted Page, Missing Query

src/UI/Content/icons.less
Because we do Music!
NO
Music Icon
=> Because we do Music!

src/UI/Settings/Notifications/Edit/NotificationEditView.js
Fixed: Twitter oAuth callback URL
NO
Sonarr/Sonarr@d7cb509
=> Fixed: Twitter oAuth callback URL

src/NzbDrone.Core/Download/TorrentClientBase.cs
Fixed: Follow 301 redirects when fetching torrents
NO
Reference Sonarr/Sonarr@755575d
=> Fixed: Follow 301 redirects when fetching torrents

src/NzbDrone.Api/Extensions/Pipelines/UrlBasePipeline.cs, src/NzbDrone.Api/Frontend/StaticResourceModule.cs, src/NzbDrone.Api/NzbDrone.Api.csproj
Fixed: Redirect calls missing URL Base
NO
Radarr/Radarr@c312ffd
Sonarr/Sonarr@de5ce23
=> Fixed: Redirect calls missing URL Base

src/NzbDrone.Api/Music/ArtistEditorModule.cs, src/NzbDrone.Api/NzbDrone.Api.csproj, src/UI/Artist/Editor/ArtistEditorFooterViewTemplate.hbs, src/UI/Artist/Editor/ArtistEditorLayout.js, src/UI/Cells/AlbumFolderCell.js
Fixed: Artist Editor View and API Back-end
NO
Fixes Artist Editor View
Adds Artist Editor API (/artist/editor)
=> Fixed: Artist Editor View and API Back-end

src/NzbDrone.Api/Config/MediaManagementConfigResource.cs, src/NzbDrone.Core.Test/MediaFiles/DiskScanServiceTests/ScanFixture.cs, src/NzbDrone.Core.Test/TvTests/EpisodeServiceTests/HandleEpisodeFileDeletedFixture.cs, src/NzbDrone.Core/Configuration/ConfigService.cs, src/NzbDrone.Core/Configuration/IConfigService.cs, src/NzbDrone.Core/MediaFiles/DiskScanService.cs, src/NzbDrone.Core/Music/TrackService.cs, src/NzbDrone.Core/Tv/EpisodeService.cs, src/UI/Settings/MediaManagement/FileManagement/FileManagementViewTemplate.hbs, src/UI/Settings/MediaManagement/Permissions/PermissionsViewTemplate.hbs, src/UI/Settings/MediaManagement/Sorting/SortingViewTemplate.hbs, src/UI/Settings/Notifications/Edit/NotificationEditViewTemplate.hbs, src/UI/Settings/Profile/Edit/EditProfileViewTemplate.hbs, src/UI/Settings/Quality/Definition/QualityDefinitionCollectionTemplate.hbs
Fixed: Refactor misc text and variables in settings
NO
=> Fixed: Refactor misc text and variables in settings

src/NzbDrone.Core/MetadataSource/SkyHook/Resource/ImageResource.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
Add Image Map and Clean SkyHookProxy
NO
Add Image Map from metadata and Clean SkyHookProxy
=> Add Image Map and Clean SkyHookProxy

src/UI/Artist/artist.less, src/UI/Shared/FormatHelpers.js
Fix Track and Album Format Issues on Artist Page
NO
Fix Track and Album Format Issues on Artist Page
=> Fix Track and Album Format Issues on Artist Page

src/NzbDrone.Api/Blacklist/BlacklistResource.cs, src/NzbDrone.Core.Test/Blacklisting/BlacklistRepositoryFixture.cs, src/NzbDrone.Core.Test/Blacklisting/BlacklistServiceFixture.cs, src/NzbDrone.Core.Test/Housekeeping/Housekeepers/CleanupOrphanedBlacklistFixture.cs, src/NzbDrone.Core/Blacklisting/Blacklist.cs, src/NzbDrone.Core/Blacklisting/BlacklistRepository.cs, src/NzbDrone.Core/Blacklisting/BlacklistService.cs, src/NzbDrone.Core/Datastore/Migration/113_music_blacklist.cs, src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedBlacklist.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Integration.Test/ApiTests/BlacklistFixture.cs, src/UI/Activity/Blacklist/BlacklistCollection.js, src/UI/Activity/Blacklist/BlacklistLayout.js, src/UI/Activity/Blacklist/BlacklistModel.js
Refactor Blacklist for Album Releases
YES
Refactor Blacklist for Album Releases
Issue #43 
*
=> Refactor Blacklist for Album Releases

src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
=> Fix Setup of NewznabRequestGenerator Test

src/NzbDrone.Core/Download/DownloadFailedEvent.cs, src/NzbDrone.Core/Download/RedownloadFailedDownloadService.cs, src/NzbDrone.Core/History/HistoryService.cs
Refactor Re-download Failed Service
NO
Refactor Re-download Failed Service
Issue #36 
*
=> Refactor Re-download Failed Service

osx/Lidarr.app/Contents/Info.plist
Update OSX Info.plist
NO
Update OSX Info.plist so as not to conflict with Sonarr
=> Update OSX Info.plist

src/NzbDrone.SignalR/NzbDronePersistentConnection.cs, src/UI/Shared/SignalRBroadcaster.js
NO
API Key for signalR connections, cherry pick from Sonarr
Sonarr/Sonarr@d257b92
*
=> API Key for signalR connections

src/NzbDrone.Api/Albums/AlbumResource.cs, src/UI/Artist/AlbumCollection.js, src/UI/Artist/Details/AlbumLayout.js, src/UI/Artist/Details/AlbumLayoutTemplate.hbs, src/UI/Artist/Details/ArtistDetailsTemplate.hbs, src/UI/Artist/TrackCollection.js, src/UI/Handlebars/Helpers/Artist.js
Get MB link working, bring in album-type from db instead of hard code, sort albums by release date, fix quirk with track number sorting, rename tool-tips
=> Fixes misc. issues on Artist Detail Page

src/UI/AddArtist/SearchResultViewTemplate.hbs
Artist overview in Search Results and Import
=> Artist overview in Search Result and Manual Import

src/UI/Navbar/Search.js
Fix Navbar Search after new DB Schema
*
=> Fix Navbar Search after new DB Schema

src/NzbDrone.Api/Config/DownloadClientConfigModule.cs, src/NzbDrone.Api/Config/DownloadClientConfigResource.cs, src/NzbDrone.Core.Test/DiskSpace/DiskSpaceServiceFixture.cs, src/NzbDrone.Core.Test/Download/CompletedDownloadServiceFixture.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/PneumaticProviderFixture.cs, src/NzbDrone.Core.Test/HealthCheck/Checks/DroneFactoryCheckFixture.cs, src/NzbDrone.Core.Test/HealthCheck/Checks/ImportMechanismCheckFixture.cs, src/NzbDrone.Core.Test/MediaFiles/DownloadedEpisodesCommandServiceFixture.cs, src/NzbDrone.Core.Test/RootFolderTests/RootFolderServiceFixture.cs, src/NzbDrone.Core/Configuration/ConfigService.cs, src/NzbDrone.Core/Configuration/IConfigService.cs, src/NzbDrone.Core/Datastore/Migration/115_change_drone_factory_variable_name.cs, src/NzbDrone.Core/DiskSpace/DiskSpaceService.cs, src/NzbDrone.Core/Download/Clients/Pneumatic/Pneumatic.cs, src/NzbDrone.Core/Download/CompletedDownloadService.cs, src/NzbDrone.Core/HealthCheck/Checks/DroneFactoryCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/ImportMechanismCheck.cs, src/NzbDrone.Core/Jobs/TaskManager.cs, src/NzbDrone.Core/MediaFiles/DownloadedEpisodesCommandService.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/RootFolders/RootFolderService.cs, src/NzbDrone.Core/Validation/Paths/DroneFactoryValidator.cs, src/UI/Settings/DownloadClient/DroneFactory/DroneFactoryViewTemplate.hbs
YES
Renames `downloadedEpisodesFolder` to `downloadedAlbumsFolder` and `downloadedEpisodesScanInterval` to `downloadedAlbumsScanInterval`
*
=> Rename Drone Factory Config Keys

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
NO
https://github.com/Sonarr/Sonarr/commit/2e392e0f5e4d0f40308f20cd1caec1c89014d87d
https://github.com/Sonarr/Sonarr/commit/5d9d2e684ebf8636c171ec684caad3c1de7fd81d
Catch-up before we start to refactor
=> New: Additional variables for custom script on grab events

src/NzbDrone.Core.Test/IndexerTests/TorrentRssIndexerTests/TorrentRssIndexerFixture.cs, src/NzbDrone.Core/Indexers/RssParser.cs
YES | NO
https://github.com/Sonarr/Sonarr/commit/94886e767b074ef4d1c219de26bf7ba82c8da1f6
=> Fixed: UnsupportedFeedException should log error for each item

src/NzbDrone.Common/Disk/DiskTransferService.cs
NO
https://github.com/Sonarr/Sonarr/commit/35741b9cae954a5474f99499a8d0063a026517c4
https://github.com/Sonarr/Sonarr/commit/f91e1a3576cb70d2987c983aec3ded70d0bd512f
=> Sonarr DiskTransferService Updates

src/NzbDrone.Update/UpdateEngine/InstallUpdateService.cs
NO
https://github.com/Sonarr/Sonarr/commit/cd450a44bf34da3720f4a1551acd2f0ce2aa313d
=> Should not empty install folder, MirrorFolder will take care of it.

src/NzbDrone.Core.Test/IndexerTests/TorrentRssIndexerTests/TorrentRssSettingsDetectorFixture.cs
NO
https://github.com/Sonarr/Sonarr/commit/924fe80997b6227693fcc6a29aee554f86ef3a4e
=> Fixed RssParser test.

src/Lidarr.Api.V1/Config/MetadataProviderConfigModule.cs
NO
Adds the ability for MetadataSource to be blank
* #113
=> Adds exception to allow metadataSource to be blank

.travis.yml, build.sh, frontend/src/Components/Link/ClipboardButton.js, frontend/src/Components/Table/Cells/RelativeDateCell.js, src/NzbDrone.Integration.Test/NzbDrone.Integration.Test.csproj
NO
Fix up build.sh and comment out the failing eslint check. Also fixes a few case inconsistencies. Set up Travis to monitor Linux build.
=> Fix Linux build and set up travis

frontend/src/System/Status/About/About.js, src/Lidarr.Api.V1/System/SystemModule.cs, src/NzbDrone.Core/Datastore/Database.cs, src/NzbDrone.Core/Datastore/LogDatabase.cs, src/NzbDrone.Core/Datastore/MainDatabase.cs
NO
Adds the DB migration version to the about page for easier troubleshooting with users.
*
=> Add DB Version to About Page

src/NzbDrone.Core.Test/Files/Indexers/Headphones/Headphones.xml, src/NzbDrone.Core.Test/IndexerTests/HeadphonesTests/HeadphonesCapabilitiesProviderFixture.cs, src/NzbDrone.Core.Test/IndexerTests/HeadphonesTests/HeadphonesFixture.cs, src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj, src/NzbDrone.Core/Indexers/Headphones/Headphones.cs, src/NzbDrone.Core/Indexers/Headphones/HeadphonesCapabilities.cs, src/NzbDrone.Core/Indexers/Headphones/HeadphonesCapabilitiesProvider.cs, src/NzbDrone.Core/Indexers/Headphones/HeadphonesRequestGenerator.cs, src/NzbDrone.Core/Indexers/Headphones/HeadphonesSettings.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Adds Headphones VIP Indexer to Lidarr (Newznab based with basic auth). Needs testing, as I dont have an account. 
*
=> New: Add Headphones VIP Indexer

src/NzbDrone.Common/Cloud/LidarrCloudRequestBuilder.cs
NO
Updates services URL to use https. Together with update server change fixes #153.
* #153
=> Fixed: Update services url to https to allow updates to work

frontend/src/Activity/Queue/RemoveQueueItemModal.js, frontend/src/Album/Search/InteractiveEpisodeSearch.js
NO
Just boring updates to reference album instead of episode.
*
=> Update text to say album instead of episode.

src/Lidarr.Api.V1/Indexers/ReleaseResource.cs, src/NzbDrone.Core.Test/DecisionEngineTests/DiscographySpecificationFixture.cs, src/NzbDrone.Core.Test/DecisionEngineTests/MonitoredAlbumSpecificationFixture.cs, src/NzbDrone.Core.Test/DecisionEngineTests/PrioritizeDownloadDecisionFixture.cs, src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj, src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs, src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs, src/NzbDrone.Core/DecisionEngine/Specifications/DiscographySpecification.cs, src/NzbDrone.Core/Music/AlbumRepository.cs, src/NzbDrone.Core/Music/AlbumService.cs, src/NzbDrone.Core/Parser/Model/ParsedAlbumInfo.cs, src/NzbDrone.Core/Parser/Parser.cs, src/NzbDrone.Core/Parser/ParsingService.cs
NO
Prioritize Discography Releases
Parse start and end date from release name and estimate which albums are in the release
Add a parser case
Cleanup
#184 
*
=> Fixed: Grab discography during artist search

src/NzbDrone.Core/MediaFiles/TrackImport/ImportApprovedTracks.cs
Fix episode reference and add case for track import permissions. Fixes #212.
NO
Fix episode reference and add case for track import permissions. Fixes #212.
* #212
=> Fix episode reference and add case for permissions error

.gitignore, frontend/.editorconfig, frontend/src/Artist/Index/Table/ArtistIndexTable.js, frontend/src/Components/Page/Header/ArtistSearchInput.css, frontend/src/Components/Page/Header/ArtistSearchInput.js
References #205
- Fixes issue when in Table mode for the artist index when you click on a letter and error was thrown
- The VirtualTable reference was not set prior to trying to access functions on the object
Also fixes another ui issue I saw, when you were in the search box, the up and down arrows would not work in the Autocomplete componenet, this fixes that.
Gitignore changes to ignore my Idea projects
=> Fixes two ui issues

src/NzbDrone.Core.Test/MusicTests/RefreshAlbumServiceFixture.cs, src/NzbDrone.Core.Test/MusicTests/ShouldRefreshAlbumFixture.cs, src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj, src/NzbDrone.Core/Music/RefreshAlbumService.cs, src/NzbDrone.Core/Music/ShouldRefreshAlbum.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Refresh album data selectively based on release date and last refresh. 
#211
=> New: Selectively refresh albums

src/Lidarr.Api.V1/Queue/QueueModule.cs
NO
Add queue size check to sort to fix #219.
* #219
=> Fixed: Add queue size check to sort to fix #219

frontend/src/AddArtist/AddNewArtist/AddNewArtist.js, frontend/src/Artist/ArtistBanner.js, frontend/src/Artist/ArtistPoster.js, frontend/src/Artist/Delete/DeleteArtistModalContent.js, frontend/src/Artist/Details/ArtistDetails.js, frontend/src/Artist/Index/Posters/ArtistIndexPosterInfo.js
NO
If poster is undefined and the "prevProps" aren't the same as the "currentProps" .. we mark the image as having a problem.
*  #169
=> WIP: Checks the props for missing poster and deals with it accordingly

src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs, src/NzbDrone.Core/Parser/Parser.cs
NO
Implements parsing usage case for Artist - Year - Album.
#264 
*
=> Implemented parsing case for Artist - Year - Album (#264)

src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowser.cs, src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs, src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserService.cs, src/NzbDrone.Core/Notifications/MediaBrowser/Model/EmbyMediaFolder.cs, src/NzbDrone.Core/Notifications/MediaBrowser/Model/EmbyMediaFoldersResponse.cs, src/NzbDrone.Core/Notifications/MediaBrowser/Model/EmbyMediaUpdateInfo.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Adds Library refresh for Emby on Album Download Notification. This is still a bit rough until Emby creates a better way to refresh on a fine grained level. 
Fixes #156 
*
=> Fixed: Update Emby Notification

frontend/src/Album/AlbumCover.js, frontend/src/Artist/ArtistBanner.js, frontend/src/Artist/ArtistPoster.js
NO
Fixes a bug in which Album Posters sometimes remain blank when previously they were loaded.
* Fixes #169
=> Fixed: Artist and Album Posters show placeholder instead of image

README.md, frontend/src/Settings/Indexers/Options/IndexerOptions.js, frontend/src/login.html, src/Lidarr.Http/Properties/AssemblyInfo.cs, src/NzbDrone.Core/Datastore/DbFactory.cs, src/NzbDrone.Host/AccessControl/SslAdapter.cs, src/NzbDrone.Host/Properties/AssemblyInfo.cs
NO
Changes GUID in host that is used to register SSL certs, Fix other Sonarr references
Fixes #306
=> Fixed: Change Host GUID, other Sonarr references

src/Lidarr.Api.V1/Commands/CommandModule.cs, src/NzbDrone.Common/Extensions/IEnumerableExtensions.cs, src/NzbDrone.Core.Test/Download/DownloadApprovedReportsTests/DownloadApprovedFixture.cs, src/NzbDrone.Core/Datastore/DbFactory.cs, src/NzbDrone.Core/Datastore/Migration/016_update_artist_history_indexes.cs, src/NzbDrone.Core/Download/Pending/PendingReleaseService.cs, src/NzbDrone.Core/Download/ProcessDownloadDecisions.cs, src/NzbDrone.Core/Messaging/Events/EventAggregator.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
YES
Few misc, pull ins from Sonarr that I was waiting on beta to bring over.
=> Sonarr pulls

src/Lidarr.Api.V1/Restrictions/RestrictionModule.cs, src/Lidarr.Api.V1/Tags/TagDetailsModule.cs, src/Lidarr.Api.V1/Tags/TagModule.cs, src/Lidarr.Http/TinyIoCNancyBootstrapper.cs, src/NzbDrone.Automation.Test/AutomationTest.cs, src/NzbDrone.Core.Test/Datastore/Converters/Int32ConverterFixture.cs, src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs, src/NzbDrone.Core/Download/Clients/Hadouken/Hadouken.cs, src/NzbDrone.Core/Download/Clients/Hadouken/HadoukenProxy.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxy.cs, src/NzbDrone.Core/ImportLists/HeadphonesImport/HeadphonesImportParser.cs, src/NzbDrone.Core/ImportLists/LidarrLists/LidarrListsParser.cs, src/NzbDrone.Core/Indexers/Gazelle/Gazelle.cs, src/NzbDrone.Core/Indexers/Headphones/HeadphonesRssParser.cs, src/NzbDrone.Core/Messaging/Commands/CommandExecutor.cs, src/NzbDrone.Host/Owin/MiddleWare/SignalRMiddleWare.cs, src/NzbDrone.Host/Owin/OwinServiceProvider.cs
NO
Fix various compiler warnings
Change OWIN appname from NzbDrone to Lidarr
=> Fixed: Compile warning cleanup

src/NzbDrone.Common.Test/Http/HttpClientFixture.cs, src/NzbDrone.Common/Http/HttpClient.cs, src/NzbDrone.Common/Http/HttpRequest.cs, src/NzbDrone.Common/Http/HttpResponse.cs
NO
https://github.com/Sonarr/Sonarr/commit/d3f8e0ef4c74877c20e71b72c0e183249e50040a
https://github.com/Sonarr/Sonarr/commit/6d8eebcd3055eaeb68b7921d82b62bb781b403e6
=> Revise cookie handling

frontend/src/Components/Form/AlbumReleaseSelectInputConnector.js, src/Lidarr.Api.V1/Albums/AlbumReleaseResource.cs, src/NzbDrone.Core/MetadataSource/SkyHook/Resource/ReleaseResource.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs, src/NzbDrone.Core/Music/AlbumRelease.cs
NO
Saves title for releases to db, shows title in release selection drop down in Album edit modal.
Fixes #329
=> New: Show Release Title on Release Selection

src/NzbDrone.Core/ImportLists/FetchAndParseImportListService.cs, src/NzbDrone.Core/ImportLists/ImportListSyncCommand.cs, src/NzbDrone.Core/ImportLists/ImportListSyncService.cs, src/NzbDrone.Core/ImportLists/ImportListUpdatedHandler.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/ThingiProvider/Events/ProviderAddedEvent.cs, src/NzbDrone.Core/ThingiProvider/ProviderFactory.cs
No
When an Import List is added or edited Lidarr will sync that specific list. Only the added/updated list will sync and it will not affect the normal import list sync schedule. 
Fixes #341
=> New: Sync Lists on Add and Update

src/NzbDrone.Core/Notifications/Subsonic/Subsonic.cs, src/NzbDrone.Core/Notifications/Subsonic/SubsonicAuthenticationException.cs, src/NzbDrone.Core/Notifications/Subsonic/SubsonicException.cs, src/NzbDrone.Core/Notifications/Subsonic/SubsonicServerProxy.cs, src/NzbDrone.Core/Notifications/Subsonic/SubsonicService.cs, src/NzbDrone.Core/Notifications/Subsonic/SubsonicSettings.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Adds Subsonic as a connection option and adds ability to update Subsonic library or Notify subsonic via Chat Message
https://feathub.com/lidarr/Lidarr/+26
=> New: Add Subsonic library update and notify

src/NzbDrone.Common/Http/HttpUri.cs, src/NzbDrone.Core/Download/Clients/Nzbget/Nzbget.cs, src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetProxy.cs, src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetSettings.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdSettings.cs, src/NzbDrone.Core/Notifications/Subsonic/SubsonicServerProxy.cs, src/NzbDrone.Core/Notifications/Subsonic/SubsonicService.cs, src/NzbDrone.Core/Notifications/Subsonic/SubsonicSettings.cs
NO
Adds ability to use sub-directories when specifying host settings for NZBGet, Sab, and Subsonic 
Fixes #386
*
=> New: Added optional UrlBase to Nzbget, Sabnzbd, and Subsonic settings

src/NzbDrone.Core/Indexers/Gazelle/Gazelle.cs, src/NzbDrone.Core/Indexers/Gazelle/GazelleApi.cs, src/NzbDrone.Core/Indexers/Gazelle/GazelleParser.cs, src/NzbDrone.Core/Indexers/Gazelle/GazelleRequestGenerator.cs, src/NzbDrone.Core/Indexers/Gazelle/GazelleSettings.cs
NO
Handle cases when Index call is null. Cleanup some things.
=> Fixed: Handle Gazelle NullRef

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs, src/NzbDrone.Core/Datastore/Migration/019_add_ape_quality_in_profiles.cs, src/NzbDrone.Core/MediaFiles/MediaFileExtensions.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/Parser/QualityParser.cs, src/NzbDrone.Core/Qualities/Quality.cs
YES
Adds support for .wv files and .ape files. Also adds qualities into the loseless group for both formats.
Fixes #454 
*
=> Added: Monkey Audio and WavPack support

frontend/src/InteractiveImport/Album/SelectAlbumRow.css, frontend/src/InteractiveImport/Album/SelectAlbumRow.js
NO
Makes entire album row clickable in manual import album selection.
=> Changed: Make entire row clickable in manual import album selection

src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
"space" is not allowed in request url
=> Fixed: Newznab "400.BadRequest"

frontend/src/Settings/Quality/Definition/QualityDefinitions.js, frontend/src/Settings/Quality/Definition/QualityDefinitionsConnector.js
Unclear UI on quality definitions page #477
Fixes #477
=> Unclear UI on quality definitions page 

src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
searchCriteria.Artist.Name includes "spaces", thus replaced by searchCriteria.ArtistQuery
=> Fixed: Newznab Artist search

src/NzbDrone.Core/ImportLists/LastFm/LastFmApi.cs, src/NzbDrone.Core/ImportLists/LastFm/LastFmParser.cs, src/NzbDrone.Core/ImportLists/LastFm/LastFmTag.cs, src/NzbDrone.Core/ImportLists/LastFm/LastFmTagRequestGenerator.cs, src/NzbDrone.Core/ImportLists/LastFm/LastFmTagSettings.cs, src/NzbDrone.Core/ImportLists/LastFm/LastFmUser.cs, src/NzbDrone.Core/ImportLists/LastFm/LastFmUserRequestGenerator.cs, src/NzbDrone.Core/ImportLists/LastFm/LastFmUserSettings.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Adds Last,fm User and Tag import lists
https://feathub.com/lidarr/Lidarr/+11
https://feathub.com/lidarr/Lidarr/+12
*
=> New: Last.fm User and Tag Import Lists

src/NzbDrone.Core/IndexerSearch/Definitions/AlbumSearchCriteria.cs, src/NzbDrone.Core/IndexerSearch/NzbSearchService.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
NO
Use Album Disambiguation/Type when searching and picking releases
Use Album Disambiguation/Type when searching and picking releases #432
*
=> Use Album Disambiguation/Type when searching and picking releases

.travis.yml
NO
Update Travis Builds to Use Node 8 LTS
=> Fixed: Update Travis Builds to Use Node 8 LTS

src/NzbDrone.Core.Test/MusicTests/TitleMatchingTests/TitleMatchingFixture.cs, src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj, src/NzbDrone.Core/Music/TrackService.cs, src/NzbDrone.Core/Parser/Parser.cs
NO
Improves TrackMatching a little bit
*
=> improve TrackMatching

src/NzbDrone.Core/Indexers/Headphones/HeadphonesRequestGenerator.cs
Fixes: `Headphones HTTP request failed: [400:BadRequest] [GET] at [https://indexer.codeshy.com/api?t=search&cat=3000,3010,3020,3030,3040&extended=1&apikey=(removed)&offset=0&limit=20&q=Anastacia Heavy%20Rotation]`
=> Fixes: Headphones album search

frontend/src/Components/SignalRConnector.js, frontend/src/Settings/ImportLists/ImportLists/EditImportListModalContent.js, frontend/src/Settings/Tags/Details/TagDetailsModalContent.js, frontend/src/Settings/Tags/Details/TagDetailsModalContentConnector.js, frontend/src/Settings/Tags/Tag.js, frontend/src/Settings/Tags/TagsConnector.js, src/Lidarr.Api.V1/Tags/TagDetailsResource.cs, src/NzbDrone.Core/Datastore/Migration/022_import_list_tags.cs, src/NzbDrone.Core/Datastore/TableMapping.cs, src/NzbDrone.Core/ImportLists/ImportListSyncService.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/Tags/TagDetails.cs, src/NzbDrone.Core/Tags/TagService.cs
YES
Allow ability to set tags that an artist will be added with from a particular import list. This allows users to better manage which artists get added from lists if they choose to.
*
=> New: Import List Tags

src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs, src/NzbDrone.Core/Configuration/AccessDeniedConfigFileException.cs, src/NzbDrone.Core/Configuration/ConfigFileProvider.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Host/Bootstrap.cs
NO
Quick fix to Prevent openflixr boot loop
*
=> New: Prevent Boot Loop if Config file Unauthorized access.

src/NzbDrone.Core/Datastore/Migration/023_add_release_groups_etc.cs, src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedArtistMetadata.cs, src/NzbDrone.Core/Music/RefreshAlbumService.cs
NO
Watch out for malformed `AlbumReleases`
Don't try to insert if Title is empty and catch and SQLite exceptions.
* Fixes #570
=> WIP: Fix migration to DB version 23

src/NzbDrone.Core.Test/IndexerTests/IPTorrentsTests/IPTorrentsFixture.cs, src/NzbDrone.Core/Indexers/IPTorrents/IPTorrentsSettings.cs
NO
Adds support for new IPTorrents RSS feed url and adds unit tests for validation
Fixes #561 
*
=> Fixed: Support new feed url format IPTorrents

frontend/src/InteractiveImport/Album/SelectAlbumRow.js, frontend/src/InteractiveImport/Interactive/InteractiveImportRow.js
NO
Show disambiguation for albums in interactive import modal.
=> Fixed: show disambiguation in interactive import modal

src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs, src/NzbDrone.Core/Parser/Parser.cs
NO
Replace accent in Album/Artist when parsing results from indexer
Fix regex to match for multiple albums
*
=> Fixed: Search Monitored to work with accent

frontend/src/Settings/DownloadClients/DownloadClients/AddDownloadClientModalContent.js
clink > click
NO
Fixing a typo. First pull req so let me know if I did it wrong.
- [no] Tests
- [no] Documentation
* n/a
=> Fix typo in AddDownloadClientModalContent.js

src/NzbDrone.Core/HealthCheck/Checks/DownloadClientCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/IndexerRssCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/IndexerSearchCheck.cs
NO
Re-evaluate Indexer and Client Health checks on a provider add.
*
=> Fixed: Re-evaluate Client/Indexer Checks on Provider Add

build.sh
NO
Add the licence file to packages
* Fixes #629
=> Fixed: Add licence to packaged files

src/NzbDrone.Common.Test/Http/HttpClientFixture.cs, src/NzbDrone.Common/Http/HttpRequestBuilder.cs, src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs, src/NzbDrone.Core/Download/Clients/Deluge/DelugeProxy.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentPreferences.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV1.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentTorrent.cs, src/NzbDrone.Core/NzbDrone.Core.csproj
NO
Pull work from Sonarr, Thanks @Taloth 
Small hack for Deluge V2 beta API issue
Fixes #594 
Fixes #595 
*
=> New: Add qBittorrent API V2 support, Indexer seed limit Support

frontend/src/Settings/MediaManagement/Naming/NamingModal.js, src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs, src/NzbDrone.Core/Organizer/FileNameBuilder.cs, src/NzbDrone.Core/Organizer/FileNameSampleService.cs
=> New: Artist Disambiguation Naming Token

src/NzbDrone.Common/Disk/DiskProviderBase.cs, src/NzbDrone.Mono.Test/DiskProviderTests/DiskProviderFixture.cs, src/NzbDrone.Mono/Disk/DiskProvider.cs, src/NzbDrone.Mono/Disk/ProcMountProvider.cs
NO
https://github.com/Sonarr/Sonarr/issues/2743
=> Fixed: DriveInfo sees snap apps, handle at higher level

src/Lidarr.Api.V1/Indexers/ReleaseModule.cs, src/NzbDrone.Common/Instrumentation/Sentry/SentryCleanser.cs, src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs, src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs, src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs, src/NzbDrone.Core/Download/Clients/Hadouken/Hadouken.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs, src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs, src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs, src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs, src/NzbDrone.Core/Extras/Metadata/MetadataService.cs, src/NzbDrone.Core/Music/AddArtistService.cs
NO
- Cleanse exception messages
- Don't add exception messages to fingerprints for all exception types to improve grouping
- Don't explicitly log exception messages - it happens automatically and breaks grouping
=> Fixed: More improvements to sentry logging

test.sh
NO
Create config directories in test script so that container tests pass.
=> Fixed: App container tests

.travis.yml
NO
Node to match Appveyor, and Yarn versions, add cache of yarn while in here
Maybe one day if appVeyor ever adds mac environment we can kill travis :)
=> New: Travis yarn cache, yarn version spec, node 10

src/NzbDrone.Core.Test/MediaFiles/AudioTagServiceFixture.cs, src/NzbDrone.Core/MediaFiles/AudioTag.cs
NO
- Don't fail if an m4a tag is missing the `day` field
- Make sure quality gets set to avoid an `NRE` in `QualityComparer` later on
=> Fixed: Some bugs in new metadata writing

src/NzbDrone.Core/Notifications/NotificationService.cs
=> Fixed: NullReferenceException in NotificationService

src/NzbDrone.Core/MediaFiles/AudioTag.cs
=> Fixed: Ensure Quality is always initialised in AudioTag.Read

src/Lidarr.Api.V1/Albums/AlbumResource.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
NO
Update artist lookup endpoint for changes in #517 
Depends on https://github.com/lidarr/LidarrAPI.Metadata/pull/101
* Fixes #690
=> Fixed: Album lookup API endpoint updated for new DB schema

appveyor-package.sh, appveyor.yml, package.json, yarn.lock
NO
Create a release and publish frontend source and sourcemaps to sentry on pushes to develop.
=> Publish js source and maps to sentry

appveyor-package.sh, appveyor.yml
NO
Update sentry auth token so it has correct permissions to associate commits
=> Fix sentry auth token

src/NzbDrone.Core.Test/MediaFiles/AudioTagServiceFixture.cs, src/NzbDrone.Core/MediaFiles/AudioTagService.cs
=> Fixed: Tag writing when release country is missing

src/NzbDrone.Mono.Test/DiskProviderTests/FreeSpaceFixture.cs, test.sh
=> Fix container and free space tests on mono

src/NzbDrone.Core.Test/MediaFiles/AudioTagServiceFixture.cs, src/NzbDrone.Core/MediaFiles/AudioTag.cs, src/NzbDrone.Core/MediaFiles/MediaFileRepository.cs, src/NzbDrone.Core/MetadataSource/SkyHook/Resource/AlbumResource.cs, src/NzbDrone.Core/MetadataSource/SkyHook/Resource/ReleaseResource.cs
NO
Various fixes for release dates - make sure initialized correctly by skyhook and written or removed correctly from tags
* fixes #705 
* Fixes LIDARR-1W6
* Issues reported on discord
=> Fix metadata dates and writing to tags

src/NzbDrone.Core/Parser/FingerprintingService.cs
NO
It looks like a minimal CentOS 7 install doesn't include `which`, which was being used to make sure `fpcalc` was on the path.  Instead, just try to run `fpcalc -version` and if it throws then assume it doesn't exist.
Also update a test broken in #709 
* Fixes Sentry LIDARR-1PS
=> Fix startup failure when `which` missing

frontend/src/System/Status/Health/Health.js, src/NzbDrone.Common/EnvironmentInfo/OsInfo.cs, src/NzbDrone.Core.Test/HealthCheck/Checks/HealthCheckFixtureExtensions.cs, src/NzbDrone.Core.Test/HealthCheck/Checks/RemotePathMappingCheckFixture.cs, src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj, src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs, src/NzbDrone.Core/HealthCheck/HealthCheckService.cs, src/NzbDrone.Core/HealthCheck/IProvideHealthCheck.cs, src/NzbDrone.Core/MediaFiles/DownloadedTracksImportService.cs, src/NzbDrone.Core/MediaFiles/TrackImport/ImportApprovedTracks.cs, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/RemotePathMappings/RemotePathMappingRepository.cs
NO
Add a healthcheck for permissions error/missing remote path mappings.  Also checks that the download client category folder is accessible.
=> New: A remote path mapping health check

frontend/src/Album/Details/AlbumDetails.js, frontend/src/Album/Details/AlbumDetailsConnector.js, frontend/src/Artist/Details/ArtistDetails.js, frontend/src/Artist/Index/ArtistIndex.js, frontend/src/Artist/Index/ArtistIndexItemConnector.js, frontend/src/Artist/Index/Banners/ArtistIndexBannersConnector.js, frontend/src/Artist/Index/Overview/ArtistIndexOverviewsConnector.js, frontend/src/Artist/Index/Posters/ArtistIndexPostersConnector.js, frontend/src/Artist/Index/Table/ArtistIndexTableConnector.js, frontend/src/Components/FileBrowser/FileBrowserModalContentConnector.js, frontend/src/Components/Form/PathInput.js, frontend/src/Components/Form/PathInputConnector.js, frontend/src/Components/Form/ProviderFieldFormGroup.js, frontend/src/Store/Actions/historyActions.js, frontend/src/Store/Actions/pathActions.js, frontend/src/Store/Selectors/createArtistSelector.js, frontend/src/Store/Selectors/createExecutingCommandsSelector.js, src/Lidarr.Api.V1/Indexers/ReleaseModule.cs, src/Lidarr.Api.V1/Indexers/ReleasePushModule.cs, src/Lidarr.Http/REST/RestModule.cs
NO
Fixes re-tag button not disabled when no track files
Fixes all buttons not disabled in albumdetail when no track files
Fixes files not included in modal and input type not recognized for custom script selection
Fixes type errors due to deletion causing issues on artist index
Fixes history columns not persisting refresh
Improve artist index render of large lists
Re-Clean release endpoints
Hopefully fix these:
Fixes LIDARR-UI-1FF
Fixes LIDARR-UI-1G8
Fixes LIDARR-UI-1G9
=> Fixed: Various UI fixes

appveyor.yml, macOS/Lidarr.app/Contents/Info.plist, setup/lidarr.iss
NO
Bump Version Commit for 0.6
=> New: Bump Version to 0.6

src/NzbDrone.Core/Datastore/DbFactory.cs
=> Fixed: Filter exception repeatedly thrown by corrupt db migration

frontend/src/Components/Page/Header/ArtistSearchInput.js, frontend/src/Components/Page/Header/ArtistSearchInputConnector.js, frontend/src/Components/Page/Header/ArtistSearchResult.js, package.json, yarn.lock
NO
Uses Fuse.js for better search results/character handling on UI page header search.
=> New: Use Fuse.js for UI header search

src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj, src/NzbDrone.Core.Test/packages.config, src/NzbDrone.Core/NzbDrone.Core.csproj, src/NzbDrone.Core/packages.config
NO
Switch to the lidarr taglib fork
=> Swap to Lidarr taglib fork

frontend/src/Activity/Queue/QueueStatusCell.js, frontend/src/Artist/Details/ArtistDetailsSeason.css, frontend/src/Artist/Details/ArtistDetailsSeason.js, frontend/src/Artist/Editor/ArtistEditorFooter.css, frontend/src/Artist/Index/ArtistIndexConnector.js, frontend/src/Components/Form/ProviderFieldFormGroup.js, frontend/src/Components/Form/TagInput.css, frontend/src/Components/Form/TagInputInput.css, frontend/src/Components/SignalRConnector.js, frontend/src/Components/Tooltip/Tooltip.js
NO
Various fixes for UI issues
#637 Maybe
*
=> Fixed: Misc UI fixes updates

frontend/src/Components/Form/DeviceInputConnector.js, frontend/src/Components/Form/ProviderFieldFormGroup.js, frontend/src/Store/Actions/index.js, frontend/src/Store/Actions/providerOptionActions.js, src/Lidarr.Http/ClientSchema/Field.cs, src/Lidarr.Http/ClientSchema/SchemaBuilder.cs, src/NzbDrone.Common.Test/ExtensionTests/StringExtensionTests/FirstCharacterToLowerFixture.cs, src/NzbDrone.Common.Test/ExtensionTests/StringExtensionTests/FirstCharcacterToLowerFixture.cs, src/NzbDrone.Common.Test/ExtensionTests/StringExtensionTests/FirstCharcacterToUpperFixture.cs, src/NzbDrone.Common.Test/NzbDrone.Common.Test.csproj, src/NzbDrone.Common/Disk/SystemFolders.cs, src/NzbDrone.Common/Extensions/StringExtensions.cs, src/NzbDrone.Common/NzbDrone.Common.csproj, src/NzbDrone.Common/Processes/ProcessProvider.cs, src/NzbDrone.Core/Annotations/FieldDefinitionAttribute.cs, src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs, src/NzbDrone.Core/Notifications/CustomScript/CustomScriptSettings.cs, src/NzbDrone.Core/Notifications/Plex/HomeTheater/PlexHomeTheaterSettings.cs, src/NzbDrone.Core/Notifications/PushBullet/PushBullet.cs, src/NzbDrone.Core/Validation/Paths/SystemFolderValidator.cs
NO
Some sonarr commits that add in hidden fields in provider forms.  Also fixes the breakage introduced in 4762c7314959a4956493d5fb06428d73ede7c12a
=> Sonarr pull as groundwork for Spotify Import lists

frontend/src/Styles/globals.css, frontend/src/index.html, frontend/src/login.html
NO
Pull from Sonarr.  Also updated login button hover colours to match Lidarr defaults (it was still using the sonarr blue)
* Fixes #854
=> Fixed: Loading of fonts.css with a URL Base

appveyor.yml
NO
Swap to previous appveyor image to fix build
=> Use previous ubuntu appveyor image

src/NzbDrone.Core/MediaFiles/Commands/RescanArtistCommand.cs, src/NzbDrone.Core/MediaFiles/DiskScanService.cs, src/NzbDrone.Core/MediaFiles/TrackImport/Identification/IdentificationService.cs, src/NzbDrone.Core/MediaFiles/TrackImport/Identification/TrackGroupingService.cs, src/NzbDrone.Core/MediaFiles/TrackImport/ImportApprovedTracks.cs, src/NzbDrone.Core/Music/AlbumEditedService.cs, src/NzbDrone.Core/Music/RefreshAlbumService.cs, src/NzbDrone.Core/Music/RefreshArtistService.cs, src/NzbDrone.Core/Music/ReleaseRepository.cs
NO
A few fixes on scanning, including making UI refresh when you change release in edit album.
=> Fixed: Various scan fixups

azure-pipelines.yml
NO
Try to fix sentry source map upload in Azure
=> Fixed: Sentry source map upload

azure-pipelines.yml
NO
Try and fix Analysis and combine with Coverage
=> Fixed: Separate Analysis Front/Back, Combine with coverage

src/NzbDrone.Common.Test/CacheTests/CachedFixture.cs, src/NzbDrone.Common.Test/ProcessProviderFixture.cs
NO
Try some tests 3 times to try and prevent build failures.
=> Fixed: Retry flaky tests 3 times before failure

frontend/src/InteractiveImport/Interactive/InteractiveImportRow.js
Fixes #848
NO
Fix UI Sort when multiple tracks are selected in manual import
Fixes #848
=> Fixed: Manual Import Tracks Sorted Wrong

src/NzbDrone.Core.Test/ParserTests/FingerprintingServiceFixture.cs, src/NzbDrone.Core/Parser/FingerprintingService.cs
NO
It's not crucial so if it fails don't take out the whole import process.
* Fixes #929
=> Fixed: Catch exceptions looking up fingerprints

build.sh, macOS/Lidarr.app/Contents/Info.plist, setup/lidarr.iss
NO
Centralize on a single place to set version numbers
=> Changed: Centralize version numbers

azure-pipelines.yml, src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs, src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
=> Changed: Version Bump 0.7.0

azure-pipelines.yml, src/NzbDrone.Common.Test/ProcessProviderFixture.cs, src/NzbDrone.Integration.Test/ApiTests/ArtistFixture.cs, src/NzbDrone.Integration.Test/ApiTests/DownloadClientFixture.cs, src/NzbDrone.Integration.Test/ApiTests/NamingConfigFixture.cs, src/NzbDrone.Integration.Test/ApiTests/RootFolderFixture.cs, src/NzbDrone.Integration.Test/GenericApiFixture.cs, src/NzbDrone.Integration.Test/HttpLogFixture.cs, src/NzbDrone.Integration.Test/IntegrationTestBase.cs, src/NzbDrone.Test.Common/NzbDroneRunner.cs, test.sh
=> Test more mono versions, tidy mac tests

src/NzbDrone.Common.Test/InstrumentationTests/SentryTargetFixture.cs, src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs
=> Filter OOM from sentry

src/NzbDrone.Console/ConsoleApp.cs
=> Fixed: Error in epic fail handler if console input redirected

azure-pipelines.yml, build.sh, frontend/src/Store/Middleware/createSentryMiddleware.js, src/Directory.Build.props, src/Directory.Build.targets, src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs, test.sh
NO
- Self hosted sentry
- Fix azure breakage
- Update mono test versions
- Bump net core
- Dedupe UI events
- Fix stack traces on linux
=> Self hosted sentry, other updates

azure-pipelines.yml
NO
Use newer Ubuntu, macos and upgrade mono on macos
*
=> Upgrade build agents

azure-pipelines.yml
=> New: Bump .NET core to 3.1.102

frontend/src/Settings/ImportLists/ImportLists/EditImportListModalContent.js, src/NzbDrone.Core/ImportLists/ImportListSyncService.cs
=> Fixed: List monitoring and adding options

azure-pipelines.yml
=> Change to Servarr TestImages

src/NzbDrone.Common.Test/DiskTests/DiskProviderFixtureBase.cs, src/NzbDrone.Common/Disk/DiskProviderBase.cs, src/NzbDrone.Mono/Disk/DiskProvider.cs
NO
Pull mono permissions error fix and cloud rename fix from Radarr.
=> Fix mono copy bug

azure-pipelines.yml
=> Update to net core 3.1.201

frontend/src/Settings/General/GeneralSettings.js, frontend/src/Settings/General/GeneralSettingsConnector.js, frontend/src/Settings/General/UpdateSettings.js, frontend/src/System/Status/About/About.js, frontend/src/System/Updates/Updates.js, src/Lidarr.Api.V1/System/SystemModule.cs, src/NzbDrone.Core/Configuration/DeploymentInfoProvider.cs, src/NzbDrone.Core/Update/ConfigureUpdateMechanism.cs, src/NzbDrone.Core/Update/InstallUpdateService.cs, src/NzbDrone.Core/Update/UpdateMechanism.cs
NO
Allow package maintainers to set branch and package version
=> New: Set Branch, Update Mech from PackageInfo

src/Lidarr.Api.V1/Artist/ArtistEditorModule.cs, src/Lidarr.Api.V1/Artist/ArtistModule.cs, src/NzbDrone.Core.Test/MusicTests/MoveArtistServiceFixture.cs, src/NzbDrone.Core/MediaFiles/MediaFileService.cs, src/NzbDrone.Core/Music/Commands/BulkMoveArtistCommand.cs, src/NzbDrone.Core/Music/Commands/MoveArtistCommand.cs, src/NzbDrone.Core/Music/Services/MoveArtistService.cs
NO
Update artist file paths when manually moving artist
* fixes #1088
=> Fixed: Update file paths correctly when moving artist

src/Lidarr.Api.V1/swagger.json
[skip-ci]
NO
Change Spec to OpenAPI 3.0.0
Add Ability for User to Set Server for Try Out
Add APIKEY security so Endpoints work
Update Endpoints
Add Tags section for Ordering of header groups
=> Fixup API Docs

src/Lidarr.Api.V1/swagger.json
=> Cleanup Swagger warnings

src/NzbDrone.Common/Disk/DiskProviderBase.cs, src/NzbDrone.Common/Disk/IDiskProvider.cs, src/NzbDrone.Core.Test/MediaFiles/DiskScanServiceTests/ScanFixture.cs, src/NzbDrone.Core/MediaFiles/DiskScanService.cs
NO
Pull from Sonarr https://github.com/Sonarr/Sonarr/commit/d3a22459ac6876a6d7966e25ac0069fbd24d72cb
=> Fixed: Performance issue when scanning large root folder

src/NzbDrone.Core.Test/IndexerTests/GazelleTests/GazelleFixture.cs, src/NzbDrone.Core.Test/IndexerTests/RedactedTests/RedactedFixture.cs, src/NzbDrone.Core/HealthCheck/Checks/RedactedGazelleCheck.cs, src/NzbDrone.Core/Indexers/Gazelle/Gazelle.cs, src/NzbDrone.Core/Indexers/Gazelle/GazelleApi.cs, src/NzbDrone.Core/Indexers/Gazelle/GazelleParser.cs, src/NzbDrone.Core/Indexers/Redacted/Redacted.cs, src/NzbDrone.Core/Indexers/Redacted/RedactedParser.cs, src/NzbDrone.Core/Indexers/Redacted/RedactedRequestGenerator.cs, src/NzbDrone.Core/Indexers/Redacted/RedactedSettings.cs
NO
- Support Redacted API keys - new indexer type and remove Gazelle preset.
- Health check for people using the old indexer setup
- Add missing media and cue info to parsed title for Gazelle and Redacted
* Fixes #1127 
* Fixes #1501
=> Redacted API Keys and Gazelle improvements

frontend/src/Components/Scroller/OverlayScroller.css, frontend/src/Components/Scroller/OverlayScroller.js, frontend/src/Store/Actions/Creators/createHandleActions.js, frontend/src/Store/Selectors/createArtistClientSideCollectionItemsSelector.js, src/Lidarr.Api.V1/Artist/ArtistResource.cs, src/NzbDrone.Core/Download/DownloadCanBeRemovedEvent.cs, src/NzbDrone.Core/Download/DownloadCompletedEvent.cs, src/NzbDrone.Core/Download/DownloadEventHub.cs, src/NzbDrone.Core/Download/DownloadProcessingService.cs, src/NzbDrone.Core/Download/TrackedDownloads/DownloadMonitoringService.cs
=> Pull more sonarr download processing commits

src/NzbDrone.Core.Test/ImportListTests/ImportListSyncServiceFixture.cs, src/NzbDrone.Core/ImportLists/ImportListSyncService.cs, src/NzbDrone.Core/MediaCover/MediaCoverService.cs, src/NzbDrone.Core/Music/Commands/RefreshAlbumCommand.cs, src/NzbDrone.Core/Music/Events/AlbumAddedEvent.cs, src/NzbDrone.Core/Music/Handlers/AlbumAddedHandler.cs, src/NzbDrone.Core/Music/Services/AddAlbumService.cs, src/NzbDrone.Core/Music/Services/AlbumService.cs, src/NzbDrone.Core/Music/Services/RefreshAlbumService.cs
NO
- Prevent duplicate rescans if an album is added for an existing artist
- Make sure album added to existing artist by import list is searched for
* More improvements for #1186
* Fixes #1105
=> More Rescan fixes

frontend/src/AlbumStudio/AlbumStudio.css, frontend/src/AlbumStudio/AlbumStudio.js, frontend/src/AlbumStudio/AlbumStudioConnector.js, frontend/src/AlbumStudio/AlbumStudioRow.css, frontend/src/AlbumStudio/AlbumStudioRow.js, frontend/src/AlbumStudio/AlbumStudioRowConnector.js, frontend/src/AlbumStudio/AlbumStudioTableHeader.css, frontend/src/AlbumStudio/AlbumStudioTableHeader.js, frontend/src/Artist/Details/ArtistDetails.js, frontend/src/Artist/Editor/ArtistEditor.js, frontend/src/Artist/Editor/ArtistEditorRow.js, frontend/src/Artist/Editor/ArtistEditorRowConnector.js, frontend/src/Artist/Index/ArtistIndexItemConnector.js, frontend/src/Artist/Index/Banners/ArtistIndexBanners.js, frontend/src/Artist/Index/Overview/ArtistIndexOverviews.js, frontend/src/Artist/Index/Posters/ArtistIndexPosters.js, frontend/src/Artist/Index/Table/ArtistIndexRow.js, frontend/src/Artist/Index/Table/ArtistIndexTable.js, frontend/src/Artist/Index/Table/ArtistStatusCell.css, frontend/src/Artist/Index/Table/ArtistStatusCell.js, frontend/src/Components/Link/Link.js, frontend/src/Components/Page/Header/PageHeader.js, frontend/src/Components/Table/Cells/VirtualTableSelectCell.js, frontend/src/Components/Table/VirtualTable.js, frontend/src/Components/withScrollPosition.js, src/Lidarr.Api.V1/Albums/AlbumModule.cs, src/NzbDrone.Core/Music/Services/AddAlbumService.cs, src/NzbDrone.Core/Music/Services/ReleaseService.cs
NO
- Speed up album studio
- Restore scroll position when returning to index page
- Make monitored flags clickable
* Fixes #1064
=> Some UI improvements

frontend/src/Settings/Indexers/Indexers/EditIndexerModalContent.js, frontend/src/Settings/Indexers/Indexers/Indexer.js, frontend/src/Settings/Indexers/Indexers/Indexers.js, src/Lidarr.Api.V1/Indexers/IndexerResource.cs, src/NzbDrone.Core.Test/DecisionEngineTests/PrioritizeDownloadDecisionFixture.cs, src/NzbDrone.Core/Datastore/Migration/044_add_priority_to_indexers.cs, src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs, src/NzbDrone.Core/Download/ProcessDownloadDecisions.cs, src/NzbDrone.Core/Indexers/IndexerBase.cs, src/NzbDrone.Core/Indexers/IndexerDefinition.cs, src/NzbDrone.Core/Parser/Model/ReleaseInfo.cs
YES (044)
Pull indexer priority from sonarr
* Closes #1571
* Closes #1579
=> Indexer priority

src/NzbDrone.Common.Test/CacheTests/CachedFixture.cs, src/NzbDrone.Common/Cache/CacheManager.cs, src/NzbDrone.Common/Cache/Cached.cs, src/NzbDrone.Core/MediaFiles/Events/RenameCompletedEvent.cs, src/NzbDrone.Core/MediaFiles/RenameTrackFileService.cs, src/NzbDrone.Core/Notifications/INotification.cs, src/NzbDrone.Core/Notifications/NotificationBase.cs, src/NzbDrone.Core/Notifications/NotificationService.cs, src/NzbDrone.Core/Notifications/Plex/Server/PlexServer.cs, src/NzbDrone.Core/Notifications/Plex/Server/PlexServerService.cs
=> Cache changes

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
| NO
Add album MBId to custom script
=> Add album MBId to custom script

src/NzbDrone.Core/Notifications/DiscordNotifier/DiscordNotifier.cs, src/NzbDrone.Core/Notifications/DiscordNotifier/DiscordNotifierException.cs, src/NzbDrone.Core/Notifications/DiscordNotifier/DiscordNotifierProxy.cs, src/NzbDrone.Core/Notifications/DiscordNotifier/DiscordNotifierSettings.cs
NO
Add a connect for Discord Notifier
=> Add a connect for Discord Notifier

frontend/src/Components/FileBrowser/FileBrowserModalContent.js, frontend/src/Settings/General/UpdateSettings.js, frontend/src/Settings/Indexers/Options/IndexerOptions.js, frontend/src/Settings/Metadata/MetadataProvider/MetadataProvider.js, frontend/src/Settings/Notifications/Notifications/NotificationEventItems.js, frontend/src/Settings/Tags/Tags.js, frontend/src/Store/Selectors/createHealthCheckSelector.js, frontend/src/System/Status/MoreInfo/MoreInfo.js, frontend/src/login.html, src/Lidarr.Api.V1/ProviderResource.cs, src/NzbDrone.Core.Test/HealthCheck/HealthCheckFixture.cs, src/NzbDrone.Core/Datastore/DbFactory.cs, src/NzbDrone.Core/HealthCheck/HealthCheck.cs, src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs, src/NzbDrone.Core/Notifications/Twitter/TwitterSettings.cs, src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
NO
Update links to use Servarr Wiki
* Fixes #1803
* Fixes #1805
=> New: Update all wiki links to point to the Servarr Wiki

README.md
=> fix readme wiki badge [skip ci]

src/NzbDrone.Core.Test/MetadataSource/SkyHook/SkyHookProxySearchFixture.cs, src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
NO
Reinstate the ability to search by artist or album musicbrainz ID in `Add New`
=> Fixed: Search by MusicBrainz ID

src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
NO
Currently albums with no valid releases show in search results, and can be added, which causes confusion.  Filter them from the search results.
* Fixes #1063
=> Fixed: Remove albums with no acceptable releases from search results

README.md
=> its 2021 [skip ci]

frontend/src/Components/Link/Link.js
=> Fixed: '/artist' URL Base breaking UI navigation

src/NzbDrone.Common.Test/DiskTests/DiskProviderFixtureBase.cs, src/NzbDrone.Common/Disk/DiskProviderBase.cs
=> Fixed: FolderWritable check for CIFS shares mounted in Unix

.github/ISSUE_TEMPLATE/bug_report.md
=> update bug template [skip ci]

src/NzbDrone.Core.Test/HealthCheck/Checks/RemotePathMappingCheckFixture.cs, src/NzbDrone.Core/HealthCheck/Checks/DownloadClientCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/DownloadClientStatusCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/FpcalcCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/ImportListStatusCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/IndexerLongTermStatusCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/IndexerStatusCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/MonoNotNetCoreCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/MonoVersionCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/MountCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/RootFolderCheck.cs
NO
update hardcoded wiki from - to _ 
* Closes #1880
=> Update wiki link hints for health checks

src/Lidarr.Api.V1/Artist/ArtistEditorModule.cs, src/Lidarr.Api.V1/Artist/ArtistModule.cs, src/NzbDrone.Core/ArtistStats/ArtistStatisticsService.cs, src/NzbDrone.Core/Blacklisting/BlacklistRepository.cs, src/NzbDrone.Core/Blacklisting/BlacklistService.cs, src/NzbDrone.Core/Download/Pending/PendingReleaseRepository.cs, src/NzbDrone.Core/Download/Pending/PendingReleaseService.cs, src/NzbDrone.Core/Extras/Files/ExtraFileRepository.cs, src/NzbDrone.Core/Extras/Files/ExtraFileService.cs, src/NzbDrone.Core/HealthCheck/Checks/RootFolderCheck.cs, src/NzbDrone.Core/History/HistoryRepository.cs, src/NzbDrone.Core/History/HistoryService.cs, src/NzbDrone.Core/ImportLists/Exclusions/ImportListExclusionService.cs, src/NzbDrone.Core/MediaCover/MediaCoverService.cs, src/NzbDrone.Core/MediaFiles/MediaFileDeletionService.cs, src/NzbDrone.Core/Music/Events/ArtistsDeletedEvent.cs, src/NzbDrone.Core/Music/Services/AlbumService.cs, src/NzbDrone.Core/Music/Services/ArtistService.cs
NO
- Speed up bulk artist deletions
- Fix bug in PendingReleases where we were deleting the PendingRelease with Id equal to Artist.Id instead of the release with ArtistId equal to Artist.Id
*
=> New: Speed up Bulk Artist Deletions

.github/ISSUE_TEMPLATE/feature_request.md
=> update FR template [skip ci]

src/Lidarr.Api.V1/Config/HostConfigModule.cs, src/NzbDrone.Core/Validation/Paths/FileExistsValidator.cs, src/NzbDrone.Host/WebHost/WebHostController.cs
NO
Pulls the existing Radarr SSL implementation for server start up
* #1942
=> Fix: SSL Web Server

.github/ISSUE_TEMPLATE/config.yml
=> update discord link

src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs
=> New: ISO 8601 Date format in log files

src/NzbDrone.Core/ImportLists/MusicBrainzSeries/MusicBrainzSeries.cs, src/NzbDrone.Core/ImportLists/MusicBrainzSeries/MusicBrainzSeriesApi.cs, src/NzbDrone.Core/ImportLists/MusicBrainzSeries/MusicBrainzSeriesParser.cs, src/NzbDrone.Core/ImportLists/MusicBrainzSeries/MusicBrainzSeriesRequestGenerator.cs, src/NzbDrone.Core/ImportLists/MusicBrainzSeries/MusicBrainzSeriesSettings.cs
NO
Allow use of MusicBrainz
This is reliant upon [https://github.com/lidarr/LidarrAPI.Metadata/pull/172](https://github.com/lidarr/LidarrAPI.Metadata/pull/172) being merged into the metadata source
=> New: MusicBrainz Series use as import list

frontend/src/Settings/ImportLists/ImportLists/EditImportListModalContent.js
NO
Adds frontend support for provider messages on Import Lists
=> Fixed: Import Lists provider message in UI

src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs
closes #2184
(cherrypicked from sonarr 8d2d9078ff8f6daf50aef2dded3f96dae93252cc)
NO
*
=> Update indexer category help text … (and make cats advanced)

.github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
=> git template update [skip ci]

src/NzbDrone.Core.Test/HealthCheck/Checks/DownloadClientRootFolderCheckFixture.cs, src/NzbDrone.Core.Test/HealthCheck/Checks/HealthCheckFixtureExtensions.cs, src/NzbDrone.Core/HealthCheck/Checks/DownloadClientRootFolderCheck.cs
NO
Health check for Downloading to Root Folder
* Fixes #2131
=> New: Health Check for Downloads to Root Folder

frontend/src/System/Tasks/Queued/QueuedTaskRow.css, frontend/src/System/Tasks/Queued/QueuedTaskRow.js, src/Lidarr.Api.V1/Commands/CommandModule.cs, src/Lidarr.Api.V1/Commands/CommandResource.cs, src/NzbDrone.Common/Http/UserAgentParser.cs, src/NzbDrone.Core/Messaging/Commands/Command.cs
NO
Show User Agent in System->Tasks for externally triggered commands - pulled from Sonarr
* Fixes #2256 
* Fixes #2260
=> New: Show User Agent in System->Tasks for externally triggered commands 

src/NzbDrone.Core/Indexers/Headphones/HeadphonesSettings.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs
No
Indexer categories are no longer an advanced option as per Sonarr.
=> New: Indexer Categories no longer an advanced option

.github/ISSUE_TEMPLATE/bug_report.md
=> Git updates

src/NzbDrone.Core/Notifications/Email/Email.cs
=> fixup radarr ref

.github/workflows/azuresync.yml
=> fix concurrency so runs don't cancel [skip ci]

.github/ISSUE_TEMPLATE/bug_report.md
(cherry picked from commit 4659a8366d8a1565890d3b72442bd35c6eb8176e)
git
closes #2320
=> Update bug report template [skip ci]

src/NzbDrone.Core/Notifications/Notifiarr/Notifiarr.cs
ref Sonarr 5938c38bc3a76d1f1e105fb54d5d7f59aa207278
(cherry picked from commit 6f0a2de5053ccb859b4ffbe1e84b4f3e0f7ef9c9)
NO
title
-  Tests
* Fixes #XXXX
=> Fixed: Notifiarr Health Issue Level

src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs
NO
Fixes misleading help text
- N/A Tests
- N/A [Wiki Updates](https://wiki.servarr.com)
* Fixes #XXXX
=> Fixed: Corrected Indexer Category Help Text

frontend/src/Components/FileBrowser/FileBrowserModalContent.js, frontend/src/Settings/General/UpdateSettings.js, frontend/src/Settings/Indexers/Options/IndexerOptions.js, frontend/src/Settings/Metadata/MetadataProvider/MetadataProvider.js, frontend/src/Settings/Notifications/Notifications/NotificationEventItems.js, frontend/src/Settings/Tags/Tags.js, frontend/src/Store/Selectors/createHealthCheckSelector.js, frontend/src/System/Status/MoreInfo/MoreInfo.js, frontend/src/login.html, src/Lidarr.Api.V1/ProviderResource.cs, src/NzbDrone.Core.Test/HealthCheck/Checks/RemotePathMappingCheckFixture.cs, src/NzbDrone.Core.Test/HealthCheck/HealthCheckFixture.cs, src/NzbDrone.Core/Datastore/DbFactory.cs, src/NzbDrone.Core/HealthCheck/Checks/DownloadClientCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/DownloadClientStatusCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/FpcalcCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/ImportListStatusCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/IndexerLongTermStatusCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/IndexerStatusCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/MountCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/RootFolderCheck.cs, src/NzbDrone.Core/HealthCheck/HealthCheck.cs, src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs, src/NzbDrone.Core/Notifications/Twitter/TwitterSettings.cs, src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
NO
Fix Supported-XXXX links
Fix/New wiki links to new wiki
-  Tests
-  Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
-  [Wiki Updates](https://wiki.servarr.com)
* Fixes #XXXX
=> New: Servarr Wiki Links | Fixed: Provider Wiki Links

README.md
Removes duplicate entries of JetBrains' products.
=> docs: remove duplicate entries

frontend/src/Components/Page/PageConnector.js, frontend/src/Settings/UI/UISettings.js, frontend/src/Settings/UI/UISettingsConnector.js, frontend/src/Store/Actions/Settings/languages.js, frontend/src/Store/Actions/settingsActions.js, frontend/src/Utilities/String/translate.js, src/Lidarr.Api.V1/Config/UiConfigResource.cs, src/Lidarr.Api.V1/Languages/LanguageController.cs, src/Lidarr.Api.V1/Languages/LanguageResource.cs, src/Lidarr.Api.V1/Localization/LocalizationController.cs, src/Lidarr.Api.V1/Localization/LocalizationResource.cs, src/NzbDrone.Core/Configuration/ConfigService.cs, src/NzbDrone.Core/Configuration/IConfigService.cs, src/NzbDrone.Core/Languages/Language.cs, src/NzbDrone.Core/Languages/LanguageExtensions.cs, src/NzbDrone.Core/Languages/LanguageFieldConverter.cs, src/NzbDrone.Core/Languages/LanguagesComparer.cs, src/NzbDrone.Core/Languages/RealLanguageFieldConverter.cs, src/NzbDrone.Core/Lidarr.Core.csproj, src/NzbDrone.Core/Localization/Core/en.json, src/NzbDrone.Core/Localization/LocalizationService.cs, src/NzbDrone.Core/Parser/IsoLanguage.cs, src/NzbDrone.Core/Parser/IsoLanguages.cs
NO
Adds localization to Lidarr to be in line with Radarr/Readarr/Prowlarr
=> New: Localization Framework

src/NzbDrone.Core/Download/Clients/Aria2/Aria2Settings.cs
closes #2465
(cherry picked from commit 44a160fa067940770525312063ce7d749f6fd212)
NO
* Fixes #XXXX
=> Clarified Aria2 RPC Path field.

src/NzbDrone.Common/Disk/DiskTransferService.cs
NO
Try reflinks on xfs as well as btrfs
* Fixes #XXXX
=> New: Support reflink on xfs

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
(cherry picked from commit beb22844c960db8e0f42a32809ad74cffce06e09)
closes #2489
=> Update Github Templates [skip ci]

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs, src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs
(cherry picked from commit 721b7ccd7bb9eaa12719b5ced1e6edd12b511260)
NO
* Fixes #XXXX
=> Fixed: Improve Log Cleansing

src/NzbDrone.Core/Indexers/FileList/FileListRequestGenerator.cs
Closes #2470
NO
-  [Wiki Updates](https://wiki.servarr.com)
* Fixes #XXXX
=> Fixed: FileList Search String

frontend/src/Search/AddNewItem.js
NO
Added release group to the help on the search page. This should save @ta264 from answering the same question over and over.
=> Adding help on release group

src/NzbDrone.Core/MediaFiles/AudioTag.cs
=> Fixed: Write ID3v2 genres as text, not a number

src/NzbDrone.Core/Localization/Core/en.json
YES - NO
Add 2 translations for UI HelpText
* Fixes #2527 
* Fixes [AB#2113](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2113)
=> Fixed: Add new translate for UI Language

src/NzbDrone.Core/Localization/Core/en.json
=> Fixed: (Translation) .Net Core to .Net

frontend/src/Store/Actions/queueActions.js
NO
Title
- Tests
* support issues
=> New: Display Unknown Items in Activity Queue by Default

src/NzbDrone.Core/Download/Clients/Flood/Flood.cs, src/NzbDrone.Core/Download/Clients/Flood/FloodProxy.cs, src/NzbDrone.Core/Download/Clients/Flood/Types/FloodClientSettings.cs
NO
Fix an issue where Flood doesn't correctly pass through the directory
=> Fixed: Avoid download path check false positives for flood

src/NzbDrone.Core/Localization/Core/fi.json, src/NzbDrone.Core/Localization/Core/hu.json, src/NzbDrone.Core/Localization/Core/pt_BR.json
Translations update from [Servarr Weblate](https://translate.servarr.com) for [Servarr/Lidarr](https://translate.servarr.com/projects/servarr/lidarr/).
Current translation status:
=> Translations update from Servarr Weblate

src/Lidarr.Http/Middleware/VersionMiddleware.cs
NO
This makes the version header consistent across Sonarr, Radarr, Prowlarr, Readarr
=> Update version header to X-Application-Version

src/NzbDrone.Update/UpdateEngine/DetectExistingVersion.cs
Fixes #2694
Closes #2700
(cherry picked from commit bc3e3714b97dec19091e45324d9f2b550f1dbbd5)
(cherry picked from commit b34f4fde1bbe611bb5c886890e3be7cec2b96e6b)
NO
* Fixes #XXXX
=> Fixed: Update from version in logs

src/NzbDrone.Common/Lidarr.Common.csproj
=> Bump SharpZipLib to 1.3.3

src/NzbDrone.Core/Notifications/Webhook/Webhook.cs, src/NzbDrone.Core/Notifications/Webhook/WebhookImportPayload.cs
NO
Expose DeleteFiles so it matches the model provided by Radarr/Sonarr
Used to trigger remove of file when upgrading
Fixes #1611
=> Add DeletedFiles on WebhookImportPayload

frontend/src/System/Status/Health/Health.js, src/NzbDrone.Core.Test/HealthCheck/Checks/IndexerJackettAllCheckFixture.cs, src/NzbDrone.Core.Test/IndexerTests/TorznabTests/TorznabFixture.cs, src/NzbDrone.Core/HealthCheck/Checks/IndexerJackettAllCheck.cs, src/NzbDrone.Core/Indexers/Torznab/Torznab.cs
(cherry picked from commit 54c914d48fefa730728518d50fc9e49032d0947b)
(cherry picked from commit 1bf87bf8735f7e7eb1b2d207d3015a7301b558bf)
NO
- Tests
* Closes #2638
* Closes #2569
=> New: End Jackett 'all' endpoint support

setup/lidarr.iss
(cherry picked from commit 8d9302da7761752189b2d2820915d7d13197ce47)
(cherry picked from commit daa9ee30a2c5fc2511e34167ce642c1bfe2a8b41)
Co-Authored By: ta264 <ta264@users.noreply.github.com>
YES - XXXX | NO
* Fixes #XXXX
=> Fixed: No longer require first run as admin on windows

.gitignore, frontend/src/Components/Page/Header/PageHeader.js, frontend/src/System/Backup/BackupRow.js, frontend/src/System/Backup/Backups.js, frontend/src/System/Status/Donations/Donations.js, src/Lidarr.Api.V1/Albums/AlbumLookupController.cs, src/Lidarr.Api.V1/Artist/ArtistLookupController.cs, src/Lidarr.Api.V1/System/Backup/BackupController.cs, src/Lidarr.Api.V1/System/Backup/BackupResource.cs, src/Lidarr.Api.V1/Tracks/TrackResource.cs, src/Lidarr.Http/Frontend/Mappers/IMapHttpRequestsToDisk.cs, src/Lidarr.Http/Frontend/Mappers/MediaCoverMapper.cs, src/Lidarr.Http/Frontend/Mappers/MediaCoverProxyMapper.cs, src/Lidarr.Http/Frontend/Mappers/StaticResourceMapperBase.cs, src/Lidarr.Http/Frontend/StaticResourceController.cs, src/NzbDrone.Core/Backup/Backup.cs, src/NzbDrone.Core/Backup/BackupService.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs, src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs, src/NzbDrone.Core/Localization/Core/en.json, src/NzbDrone.Core/MediaCover/MediaCover.cs, src/NzbDrone.Core/MediaCover/MediaCoverProxy.cs, src/NzbDrone.Core/MediaCover/MediaCoverService.cs, src/NzbDrone.Core/MediaFiles/TrackImport/ImportApprovedTracks.cs, src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
NO
MediaCovers and Discord Import
* Fixes #1355
* Fixes #2598 
* Fixes #2669 
* Fixes #2443
* Fixes #1288
=> Radarr pulls

azure-pipelines.yml, build.sh, package.json, src/NzbDrone.Core.Test/UpdateTests/UpdatePackageProviderFixture.cs, src/NzbDrone.Integration.Test/Lidarr.Integration.Test.csproj, src/NzbDrone.Mono.Test/Lidarr.Mono.Test.csproj, src/NzbDrone.Mono/Lidarr.Mono.csproj, yarn.lock
NO
Add linux-x86 builds
* Fixes #2772
=> Linux x86 builds

build.sh
This reverts commit 45ab2b2409fd11c556c1374aec8d27aec898c4fc.
=> Revert "Allow build script to produce packages on non-windows OSes"

src/NzbDrone.Update/UpdateEngine/InstallUpdateService.cs
fixup 9a5ec50e78078d864fea873ca9fbb2ca4455b20d
NO
Make fpcalc executable as well
- Tests
* Fixes #XXXX
=> Fixed: Fpcalc not executable after update

frontend/src/App/App.js, frontend/src/Components/Page/PageContent.js, frontend/src/Settings/General/HostSettings.js, src/Lidarr.Api.V1/Config/HostConfigController.cs, src/Lidarr.Api.V1/Config/HostConfigResource.cs, src/Lidarr.Api.V1/System/SystemController.cs, src/Lidarr.Http/Frontend/InitializeJsController.cs, src/NzbDrone.Core/Configuration/ConfigFileProvider.cs, src/NzbDrone.Core/Instrumentation/ReconfigureLogging.cs, src/NzbDrone.Core/Lidarr.Core.csproj, src/NzbDrone.Core/Localization/Core/en.json, src/NzbDrone.Core/Validation/RuleBuilderExtensions.cs
(cherry picked from commit 8d856b2edb8bf46a2b516d5f7644ae3fa1151323)
NO
Support Syslog Support using configuration in config.xml as per implementation in Prowlarr
=> New: Added UDP syslog support

src/NzbDrone.Core/ImportLists/LastFm/LastFmTagSettings.cs, src/NzbDrone.Core/ImportLists/LastFm/LastFmUserSettings.cs
This will protect us from both MITM attacks, and also increase the
privacy of users.
=> Connect to audioscrobbler via https

src/NzbDrone.Core.Test/MediaFiles/TrackImport/ImportDecisionMakerFixture.cs, src/NzbDrone.Core/MediaFiles/TrackImport/ImportDecisionMaker.cs
NO
If a user had multiple versions of an album on disk and import their library to Lidarr, multiple versions get accepted and things go wrong.
=> Fixed: Only one version of an album may be approved for import

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs, src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs
Fixed: Cleanse Notifiarr secret from URL in logs
Closes #2611
(cherry picked from commit e6210aede6f7ead197e82572976bc0267d910d46)
Closes #2557
(cherry picked from commit ec866082d44d299096112a6c7c232384b1f74505)
YES - XXXX | NO
* Fixes #XXXX
=> Fixed: Better Cleansing of Tracker Announce Keys

src/Lidarr.Api.V1/Artist/ArtistController.cs, src/NzbDrone.Core/ArtistStats/ArtistStatisticsService.cs, src/NzbDrone.Core/Music/Services/RefreshAlbumService.cs
NO
When an album's artist changed it tried to add the new artist but didn't correctly set the root folder so it failed.
Correctly push the required updates to the UI.
* Fixes LIDARR-H
=> Fixed: Correctly add missing new artist when an album's artist changes in musicbrainz

src/NzbDrone.Core.Test/Download/DownloadClientTests/Blackhole/TorrentBlackholeFixture.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabCategoryFieldOptionsConverter.cs
NO
Correct a typo: _loseless_ should be _lossless_.
=> Fix typo: loseless to lossless

src/Lidarr.Api.V1/Queue/QueueController.cs, src/NzbDrone.Core.Test/DecisionEngineTests/RepackSpecificationFixture.cs, src/NzbDrone.Core.Test/IndexerSearchTests/SearchDefinitionFixture.cs, src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabCapabilitiesProviderFixture.cs, src/NzbDrone.Core/DecisionEngine/Specifications/RepackSpecification.cs, src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs, src/NzbDrone.Core/Download/DownloadIgnoredEvent.cs, src/NzbDrone.Core/Download/IgnoredDownloadService.cs, src/NzbDrone.Core/History/EntityHistoryService.cs, src/NzbDrone.Core/IndexerSearch/Definitions/AlbumSearchCriteria.cs, src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs, src/NzbDrone.Core/Indexers/FileList/FileListRequestGenerator.cs, src/NzbDrone.Core/Indexers/Gazelle/GazelleRequestGenerator.cs, src/NzbDrone.Core/Indexers/Headphones/HeadphonesRequestGenerator.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabCapabilities.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs, src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs, src/NzbDrone.Core/Indexers/Rarbg/RarbgRequestGenerator.cs, src/NzbDrone.Core/Indexers/Redacted/RedactedRequestGenerator.cs, src/NzbDrone.Core/Localization/Core/en.json, src/NzbDrone.Core/Notifications/Webhook/Webhook.cs, src/NzbDrone.Core/Notifications/Webhook/WebhookRetagPayload.cs
No
Sonarr Pulls
* Fixes #1951
* Fixes #2601
* Fixes #2620 
* Fixes #2749 
* Fixes #2995 
* Fixes #2996
* Fixes #2999
* Closes #2750
=> Added searchEngine support in Newznab/Torznab caps

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs, src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs, src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrException.cs, src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrProxy.cs
NO
Pending Notifiarr changes
- Tests
* Fixes #XXXX
=> New: Notifiarr moved from webhook to API

src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrProxy.cs, src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrSettings.cs
NO
hotfix typo and logic rework to stop double logging errors per Markus PR comments on https://github.com/Sonarr/Sonarr/pull/5168
- Tests
* Fixes #XXXX
=> Notifiarr Fixups - fix invalid/broken url

frontend/src/Components/SignalRConnector.js, frontend/src/InteractiveImport/AlbumRelease/SelectAlbumReleaseModalContent.js, src/Lidarr.Api.V1/ProviderResource.cs, src/NzbDrone.Common.Test/Http/HttpClientFixture.cs, src/NzbDrone.Common/EnvironmentInfo/AppFolderFactory.cs, src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs, src/NzbDrone.Common/OAuth/OAuthTools.cs, src/NzbDrone.Common/ServiceProvider.cs, src/NzbDrone.Core/Datastore/ExpressionVisitor.cs, src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs, src/NzbDrone.Core/DecisionEngine/Specifications/UpgradableSpecification.cs, src/NzbDrone.Core/Download/Clients/Transmission/TransmissionProxy.cs, src/NzbDrone.Core/Extras/Metadata/ExistingMetadataImporter.cs, src/NzbDrone.Core/HealthCheck/Checks/DownloadClientRootFolderCheck.cs, src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs, src/NzbDrone.Core/History/EntityHistoryService.cs, src/NzbDrone.Core/MediaFiles/TrackImport/ImportApprovedTracks.cs, src/NzbDrone.Core/MediaFiles/TrackImport/Specifications/ArtistPathInRootFolderSpecification.cs, src/NzbDrone.Core/Notifications/Mailgun/Mailgun.cs, src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserSettings.cs, src/NzbDrone.Core/Notifications/Twitter/TwitterService.cs, src/NzbDrone.Core/Parser/FingerprintingService.cs, src/NzbDrone.Core/Parser/Parser.cs, src/NzbDrone.Host/UtilityModeRouter.cs
Found via `codespell -q3 -S ./yarn.lock,./src/NzbDrone.Core.Test,./src/NzbDrone.Core/Localization -L bitap,tempdate,uptodate`
=> Fix various typos

src/NzbDrone.Core/Music/Repositories/AlbumRepository.cs
NO
Fixup for #2625 that shouldn't have been removed - tested locally and seems to work.
=> Fix: Restore missing groupbys in AlbumRepo

frontend/src/Album/Details/AlbumDetailsMedium.css, frontend/src/AlbumStudio/AlbumStudioAlbum.css, frontend/src/Artist/Index/Banners/ArtistIndexBannerInfo.css, frontend/src/Artist/Index/Posters/ArtistIndexPoster.css, frontend/src/Artist/Index/Posters/ArtistIndexPosterInfo.css, frontend/src/Search/Album/AddNewAlbumSearchResult.css, frontend/src/Search/Artist/AddNewArtistSearchResult.css, frontend/src/Styles/Themes/dark.js, frontend/src/Styles/Themes/light.js, frontend/src/TrackFile/ExpandingFileDetails.css
NO
Fixup some theme flashbangs on search and manual import
- N/A
* N/A
=> Fixup Theme CSS

src/NzbDrone.Core/Backup/BackupService.cs
YES - NO
Stops trying to backup SQLite database when using Postgres database
=> Fixed: No longer tries to backup database when using Postgres

frontend/src/AlbumStudio/AlbumStudioAlbum.css
NO
Fixup Album Studio
- N/A
* N/A
=> Fixup Album Studio

src/NzbDrone.Core/ArtistStats/ArtistStatisticsRepository.cs, src/NzbDrone.Core/Datastore/Migration/030_add_mediafilerepository_mtime.cs
NO
`true` only works after Sqlite 3.23
=> Fixed: Restore old Sqlite version compatibility

src/NzbDrone.Core/Configuration/ConfigFileProvider.cs, src/NzbDrone.Host/Startup.cs
(cherry picked from commit 5326a102e23eacfc1132eb544a92af737a531df5)
NO
=> Fixed: Ensure default config file on starting app

frontend/src/Artist/Delete/DeleteArtistModalContent.js, src/NzbDrone.Core/Localization/Core/en.json
=> Fixed: (UI) Show the correct path in delete artist modal

src/NzbDrone.Core/Download/History/DownloadHistoryService.cs, src/NzbDrone.Core/History/EntityHistoryService.cs
=> Fixed: Null reference processing failed import for unknown album

src/NzbDrone.Core.Test/NotificationTests/EmailTests/EmailSettingsValidatorFixture.cs, src/NzbDrone.Core/Notifications/Email/Email.cs, src/NzbDrone.Core/Notifications/Email/EmailSettings.cs
=> Rename `CC` to `Cc`

src/NzbDrone.Core.Test/IndexerTests/GazelleTests/GazelleFixture.cs, src/NzbDrone.Core/Indexers/Gazelle/GazelleParser.cs
NO
Fixes grabbing for Orpheus.
=> Fixed: (Gazelle) Add `usetoken` only if use FL token is enabled

src/NzbDrone.Core/History/EntityHistoryService.cs
=> Fixed: Null reference processing import with no download client info

src/NzbDrone.Core.Test/IndexerTests/RedactedTests/RedactedFixture.cs, src/NzbDrone.Core/Indexers/Redacted/Redacted.cs, src/NzbDrone.Core/Indexers/Redacted/RedactedParser.cs, src/NzbDrone.Core/Indexers/Redacted/RedactedRequestGenerator.cs, src/NzbDrone.Core/Indexers/Redacted/RedactedSettings.cs
=> Fixed: Ignore `VA` artists in Redacted

frontend/src/Components/Form/ProviderFieldFormGroup.js, src/Lidarr.Http/ClientSchema/Field.cs, src/Lidarr.Http/ClientSchema/SchemaBuilder.cs, src/NzbDrone.Core/Annotations/FieldDefinitionAttribute.cs, src/NzbDrone.Core/Notifications/Apprise/Apprise.cs, src/NzbDrone.Core/Notifications/Apprise/AppriseError.cs, src/NzbDrone.Core/Notifications/Apprise/AppriseException.cs, src/NzbDrone.Core/Notifications/Apprise/AppriseNotificationType.cs, src/NzbDrone.Core/Notifications/Apprise/ApprisePayload.cs, src/NzbDrone.Core/Notifications/Apprise/AppriseProxy.cs, src/NzbDrone.Core/Notifications/Apprise/AppriseSettings.cs
=> New: (Notifications) Add Apprise

frontend/src/InteractiveImport/Interactive/InteractiveImportModalContentConnector.js
NO
Check the Key value not the translate key
- [] Tests
- [] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [] [Wiki Updates](https://wiki.servarr.com)
* Fixes #XXXX
=> Fixed: Show Error Message if no Manual Import Mode selected

frontend/src/Settings/MediaManagement/Naming/NamingModal.js, src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs, src/NzbDrone.Core/Organizer/FileNameBuilder.cs, src/NzbDrone.Core/Organizer/FileNameSampleService.cs
NO
Added options for **{Artist Id}**, **{Album Id}**, and **{Track ArtistId}** to file and folder naming process. Includes new test cases.
* Fixes #2872
=> New: {Artist Id}, {Album Id}, and {Track ArtistId} options in file/folder naming.

src/NzbDrone.Common.Test/Http/HttpClientFixture.cs, src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs
=> Improved http timeout handling

src/NzbDrone.Core/Datastore/Migration/072_add_alac_24_quality_in_profiles.cs, src/NzbDrone.Core/Parser/QualityParser.cs, src/NzbDrone.Core/Profiles/Qualities/QualityProfileService.cs, src/NzbDrone.Core/Qualities/Quality.cs
Yes - 072
Add an ALAC 24bit quality
* Fixes #621
=> Add ALAC 24bit

src/NzbDrone.Core.Test/MediaFiles/AudioTagServiceFixture.cs, src/NzbDrone.Core/MediaFiles/AudioTagService.cs
Don't blitz replaygain tags, bump taglib
* Fixes #1086
=> Replay tags

frontend/src/Settings/Metadata/MetadataProvider/MetadataProvider.js, src/Lidarr.Api.V1/Config/MetadataProviderConfigResource.cs, src/NzbDrone.Core.Test/MediaFiles/AudioTagServiceFixture.cs, src/NzbDrone.Core/Configuration/ConfigService.cs, src/NzbDrone.Core/Configuration/IConfigService.cs, src/NzbDrone.Core/Localization/Core/en.json, src/NzbDrone.Core/MediaFiles/AudioTagService.cs
Add an option to disable album cover embed into audio files
* Fixes #2488
=> New: Option to disable cover art embed in files
